'use client';
import {useEffect,useRef,useState} from 'react';
import type {Category,Facts,CandidateContent} from '@/app/lib/review/contracts';
import {ReviewFailure} from '@/app/lib/review/contracts';
import {classificationCategories,classificationCommand,classificationDetail,classificationDraft,classificationFields,classificationFilters,classificationFilterFacts,classificationMissing,classificationMatches,classificationApplyCommand} from '@/app/lib/review/classification';
import type {ClassificationDetail} from '@/app/lib/review/classification';
import type {ContentFilters} from '@/app/lib/contentFilters';
import {categories,failureText,reasonText} from '@/app/lib/review/presentation';
import {factLabels} from '@/app/lib/review/facts-guidance';
import {FactsEditor,CandidateEditor,fieldClass,primaryButton,secondaryButton} from './ReviewEditors';
import {reviewOverview,reviewError,reviewDirty} from './ReviewStates';
import {FilterInputs,reviewFilterLabel} from './FilterReviewPanel';

async function request(id:string,body?:unknown,signal?:AbortSignal) {
  const r=await fetch(`/api/admin/review-classification/${id}`,{cache:'no-store',credentials:'same-origin',signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
  const b=await r.json().catch(()=>null);
  if(!r.ok)throw new ReviewFailure(b?.code??'unavailable',b?.fields);
  return classificationDetail(b?.item,id);
}
export default function ClassificationPanel({id,disabled,onBlocked,onActive,onSaved}:{id:string;disabled:boolean;onBlocked:(v:boolean)=>void;onActive:(v:boolean)=>void;onSaved?:()=>Promise<void>}) {
  const[item,setItem]=useState<ClassificationDetail|null>(null),[facts,setFacts]=useState<Facts|null>(null),[filters,setFilters]=useState<ContentFilters|null>(null);
  const[opened,setOpened]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState('');
  const[errors,setErrors]=useState<Record<string,string>>({}),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false);
  const[editorKey,setEditorKey]=useState(0),[checked,setChecked]=useState(false);
  const sending=useRef(false),region=useRef<HTMLElement>(null);
  const attempted=useRef<ReturnType<typeof classificationCommand>|null>(null);
  const drafts=useRef<Partial<Record<Category,{facts:Facts;filters:ContentFilters|null}>>>({});
  const appliedAttempt=useRef<ReturnType<typeof classificationApplyCommand>|null>(null);
  const[publicOpened,setPublicOpened]=useState(false),[publicContent,setPublicContent]=useState<CandidateContent|null>(null),[publicChecked,setPublicChecked]=useState(false),[publicNote,setPublicNote]=useState('');
  const dirty=Boolean(opened&&item&&(JSON.stringify(facts)!==JSON.stringify(item.facts)||JSON.stringify(filters)!==JSON.stringify(item.filters)||note!==item.note||pending));
  useEffect(()=>{const c=new AbortController();request(id,undefined,c.signal).then(next=>{if(c.signal.aborted)return;setItem(next);setFacts(next.facts);setFilters(next.filters);setNote(next.note);onActive(next.active);}).catch(e=>{if(!c.signal.aborted)setError(failureText[e.code]??'분류 상태를 불러오지 못했습니다.');});return()=>c.abort();},[id,onActive]);
  useEffect(()=>{onBlocked(busy||opened||publicOpened);return()=>onBlocked(false);},[busy,opened,publicOpened,onBlocked]);
  useEffect(()=>{onActive(Boolean(item?.active||opened));},[item?.active,opened,onActive]);
  useEffect(()=>{if(!dirty&&!publicOpened)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,publicOpened]);
  function accept(next:ClassificationDetail){setItem(next);setFacts(next.facts);setFilters(next.filters);setNote(next.note);setPending(false);setUncertain(false);setChecked(false);setEditorKey(k=>k+1);drafts.current={};onActive(next.active);}
  async function read(){if(sending.current)return;setBusy(true);try{const next=await request(id);const sent=attempted.current;
    if(uncertain&&appliedAttempt.current&&next.publication?.applied&&next.classificationVersion===appliedAttempt.current.classificationVersion&&JSON.stringify(next.publication.content)===JSON.stringify(appliedAttempt.current.content)){accept(next);setPublicOpened(false);setError('');setNotice('읽기 확인으로 이전 공개 재분류 적용 완료를 확인했습니다. 다시 쓰지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('읽기 확인으로 저장 완료를 확인했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}
    else if(uncertain&&sent&&classificationMatches(next,sent)){accept(next);setOpened(false);setError('');setNotice('읽기 확인으로 이전 분류 저장 완료를 확인했습니다. 새 저장·AI 실행은 하지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('읽기 확인으로 저장 완료를 확인했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}
    else{setItem(next);onActive(next.active);setChecked(false);setPublicChecked(false);setNotice('현재 저장 상태를 확인했습니다. 입력은 유지했습니다. 최신 저장값과 보존한 입력을 다시 대조하세요. 확인 체크는 해제했습니다. 최신 저장값을 사용하려면 입력 취소를 선택하세요.');}
  }catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'상태 확인 실패':'상태 확인 실패');}finally{setBusy(false);}}
  if(!item||!facts)return <section className="my-5" aria-label="분류 변경">{error&&<p role="alert" className="text-info-status">{error}</p>}</section>;
  const missing=[...new Set(classificationMissing(facts,filters).map(k=>filters&&facts.category==='program'&&k==='delivery'?'filter:delivery':filters&&facts.category==='program'&&['deadlineKind','deadlineOn'].includes(k)?'filter:application':filters&&facts.category==='event'&&['eventStart','eventEnd'].includes(k)?'filter:schedule':k))];
  const label=(k:string)=>k.startsWith('filter:')&&filters?reviewFilterLabel(filters,k.slice(7) as ReturnType<typeof classificationFields>[number]):factLabels[k as keyof Facts]??k;
  function jump(k:string){const node=region.current?.querySelector<HTMLElement>(k.startsWith('filter:')?`[data-filter-key="${k.slice(7)}"]`:`[id="classification-${k}"]`);const control=node?.matches('input,select,textarea')?node:node?.querySelector<HTMLElement>('input,select,textarea,button');(control??node)?.focus();node?.scrollIntoView({block:'center'});}
  return <section ref={region} className="my-6 border-b border-info-rule pb-6" aria-label="공통 카테고리 검토" aria-busy={busy}>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="font-semibold">카테고리: {item.category?categories[item.category]:'분류 확인 필요'}</p><button type="button" className={secondaryButton} disabled={disabled||busy||publicOpened||!item.editable||opened&&dirty} onClick={()=>{setOpened(v=>!v);setError('');appliedAttempt.current=null;}}>{opened?'분류 변경 닫기':item.active?'분류·필수값 다시 확인':'분류 변경'}</button></div>
    {!item.editable&&<p className="mt-2 text-sm text-info-muted">처리 중이거나 제외된 항목입니다. 기존 처리 상태를 먼저 확인해 주세요.</p>}
    {item.active&&!opened&&<p className="mt-3 leading-7 text-info-body">{item.ready?'새 분류의 사실·필터 확인을 마쳤습니다. 후보 처리는 별도 실행입니다.':'새 분류에 남은 확인사항이 있습니다. 분류·필수값을 다시 확인해 주세요.'}</p>}
    {opened&&<form className="mt-5 space-y-6" onSubmit={async e=>{e.preventDefault();if(sending.current||disabled||pending||uncertain)return;setError('');setErrors({});let body;try{body=classificationCommand({revision:item.revision,version:item.version,classificationVersion:item.classificationVersion,facts,filters,note});}catch(e){setError('새 분류의 필수값과 원문 근거를 확인해 주세요. 입력은 유지합니다.');if(e instanceof ReviewFailure)setErrors(e.fields);return;}if(!checked){setError('유지할 값과 다시 확인한 값을 검토한 뒤 확인 체크를 선택해 주세요.');return;}attempted.current=body;appliedAttempt.current=null;sending.current=true;setBusy(true);try{const next=await request(id,body);accept(next);setOpened(false);if(onSaved){try{await onSaved();}catch{setNotice("분류 저장은 완료했지만 기존 검토 상태를 새로 읽지 못했습니다. 최신 상태를 다시 확인해 주세요.");return;}}setNotice(next.ready?'분류와 필수값을 함께 저장·재판정했습니다. AI는 실행하지 않았습니다.':'분류를 저장했습니다. 남은 사실 확인을 마쳐야 후보 처리가 가능합니다.');}catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'저장 결과를 확인하지 못했습니다.':'저장 결과를 확인하지 못했습니다.');if(!(e instanceof ReviewFailure)||e.code==='unavailable')setUncertain(true);}finally{sending.current=false;setBusy(false);}}}>
      <label className="block font-semibold">새 카테고리<select className={fieldClass} value={facts.category} disabled={busy||uncertain} required onChange={e=>{const cat=e.target.value as Category;drafts.current[facts.category]={facts:structuredClone(facts),filters:structuredClone(filters)};const restored=drafts.current[cat];setFacts(restored?structuredClone(restored.facts):classificationDraft(facts,cat));setFilters(restored?structuredClone(restored.filters):classificationFilters(cat,filters));setPending(false);setEditorKey(k=>k+1);setChecked(false);}}><option value="" disabled>선택해 주세요</option>{classificationCategories.map(c=><option key={c} value={c}>{categories[c]}</option>)}</select></label>
      <section className={reviewOverview} aria-label="재분류 확인사항"><h3 className="font-bold">이번에 확인할 사항 · {missing.length}개</h3><p className="mt-2 text-sm leading-6 text-info-muted">카테고리를 다시 선택하면 해당 분류의 입력 초안을 복원합니다. 실제 지역은 유지하며 신청 마감일과 행사 개최일은 서로 변환하지 않습니다. 저장 전 원문 근거를 다시 확인하세요.</p>
        {missing.length?<ul className="mt-3 flex flex-wrap gap-x-4 gap-y-2">{missing.map(k=><li key={k}><button type="button" className="min-h-11 py-2 font-semibold underline underline-offset-4" onClick={()=>jump(k)}>{label(k)} · 확인 필요</button></li>)}</ul>:<p className="mt-3 text-info-body">필수 입력이 채워졌습니다. 저장 전 원문 근거를 확인해 주세요.</p>}
        {item.sourceReasons.length>0&&<p className="mt-3 text-sm leading-6 text-info-status">별도 사실 확인: {item.sourceReasons.map(r=>reasonText(r).title).join(' · ')}. 기존 사실 검토에서 확인하며, 분류 변경으로 자동 해소하지 않습니다.</p>}
      </section>
      {filters&&<FilterInputs key={editorKey} data={filters} fields={classificationFields(facts.category)} onChange={v=>{setFilters(v);setFacts(classificationFilterFacts(facts,v));setChecked(false);}} disabled={busy||uncertain} onPending={setPending} missing={missing.filter(k=>k.startsWith('filter:')).map(k=>k.slice(7))} saved={item.filters??undefined} prefix="classification" confirmed={item.active&&facts.category===item.category?classificationFields(item.category).filter(k=>(item.filters?.[k].status==='known'||item.filters?.[k].status==='not_applicable')&&!classificationMissing(item.facts,item.filters).includes(`filter:${k}`)):[]}/>}
      <FactsEditor idPrefix="classification-" value={facts} onChange={v=>{setFacts(v);setChecked(false);}} errors={errors} disabled={busy||uncertain} missing={missing} saved={item.facts} confirmed={item.active&&facts.category===item.category} editableFields={(Object.keys(facts) as (keyof Facts)[]).filter(k=>k!=='category'&&!(facts.category==='program'&&['delivery','deadlineKind','deadlineOn'].includes(k))&&!(facts.category==='event'&&['eventStart','eventEnd'].includes(k)))}/>
      <label className="block font-semibold">분류와 필수값의 확인 근거<textarea className={fieldClass} rows={3} maxLength={4000} minLength={10} required value={note} disabled={busy||uncertain} onChange={e=>{setNote(e.target.value);setChecked(false);}}/><span className="mt-2 block text-sm font-normal leading-6 text-info-muted">공식 원문의 근거와 분류 이유를 기록하세요. 선택값에서 원문 인용을 자동 생성하지 않습니다.</span></label>
      <label className="flex min-h-11 items-start gap-3"><input type="checkbox" className="mt-1 size-5 accent-ink" checked={checked} disabled={busy||uncertain} onChange={e=>setChecked(e.target.checked)}/><span>유지할 값과 새 분류의 필수값·원문 근거를 확인했습니다.</span></label>
      {dirty&&<p className={reviewDirty}>미저장 변경이 있습니다.</p>}
      <div className="flex flex-wrap gap-3"><button type="submit" className={primaryButton} disabled={busy||uncertain||pending}>{busy?'저장 중…':'분류·필수값 저장·재판정'}</button><button type="button" className={secondaryButton} disabled={busy} onClick={()=>{accept(item);setOpened(false);setError('');}}>입력 취소</button></div>
    </form>}
    {item.publication&&<section className="mt-5 border-t border-info-rule pt-5" aria-label="공개 콘텐츠 재분류 적용">
      <p className="font-semibold">현재 공개 분류: {item.publication.category?categories[item.publication.category]:"분류 확인 필요"}</p>
      <p className="mt-2 leading-7">검토 중에는 기존 공개본을 유지합니다. 새 분류와 한국어·일본어 본문을 확인한 뒤 명시적으로 적용합니다. 콘텐츠 ID·URL·저장·댓글은 유지합니다. AI는 실행하지 않습니다.</p>
      {!publicOpened&&<button type="button" className={`${secondaryButton} mt-3`} disabled={disabled||busy||opened||!item.active||!item.ready||item.publication.applied} onClick={()=>{setPublicContent(structuredClone(item.publication!.content));setPublicNote('');setPublicChecked(false);setPublicOpened(true);setError('');attempted.current=null;appliedAttempt.current=null;}}>{item.publication.applied?'현재 분류 적용 완료':'공개 본문 확인·재분류 적용'}</button>}
      {publicOpened&&publicContent&&<form className="mt-5 space-y-5" onSubmit={async e=>{e.preventDefault();if(sending.current||disabled||uncertain||!publicChecked)return;let body;try{body=classificationApplyCommand({action:'apply_public',revision:item.revision,version:item.version,classificationVersion:item.classificationVersion,publicationVersion:item.publication!.version,content:publicContent,bodyReviewed:publicChecked,note:publicNote});}catch{setError('두 언어의 본문과 적용 근거를 확인해 주세요. 입력은 유지합니다.');return;}appliedAttempt.current=body;sending.current=true;setBusy(true);setError('');try{const next=await request(id,body);accept(next);setPublicOpened(false);setNotice('공개 카테고리·필터·확인한 본문을 함께 적용했습니다. AI를 실행하지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('공개 재분류 적용은 완료했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'적용 결과를 확인하지 못했습니다.':'적용 결과를 확인하지 못했습니다.');if(!(e instanceof ReviewFailure)||e.code==='unavailable')setUncertain(true);}finally{sending.current=false;setBusy(false);}}}>
        <p className={reviewOverview}>적용할 분류: <strong>{item.category?categories[item.category]:"분류 확인 필요"}</strong> · 필요한 본문 수정도 이 적용 요청에서 함께 저장됩니다.</p>
        {JSON.stringify(publicContent)!==JSON.stringify(item.publication.content)&&<details className="border-y border-info-rule py-3"><summary className="min-h-11 cursor-pointer font-semibold">현재 공개본과 수정 입력 대조</summary><p className="my-3">아래는 현재 공개된 저장본이며 작성 중인 입력은 다음 편집란에 보존합니다. 다른 검토자의 변경을 덮어쓰지 않도록 대조 후 다시 확인하세요.</p>{Object.entries(item.publication.content).map(([k,v])=><div key={k} className="mb-4"><p className="font-semibold">{({titleKo:'한국어 제목',summaryKo:'한국어 요약',contentKo:'한국어 본문',titleJa:'일본어 제목',summaryJa:'일본어 요약',contentJa:'일본어 본문'} as Record<string,string>)[k]}</p><p className="whitespace-pre-wrap break-words">{v||'비어 있음'}</p></div>)}</details>}
        <CandidateEditor value={publicContent} onChange={v=>{setPublicContent(v);setPublicChecked(false);}} errors={{}} disabled={busy||uncertain}/>
        <label className="block font-semibold">공개 적용 근거<textarea className={fieldClass} minLength={10} maxLength={4000} required rows={3} value={publicNote} disabled={busy||uncertain} onChange={e=>{setPublicNote(e.target.value);setPublicChecked(false);}}/></label>
        <label className="flex min-h-11 items-start gap-3"><input type="checkbox" checked={publicChecked} disabled={busy||uncertain} onChange={e=>setPublicChecked(e.target.checked)}/><span>새 분류와 필터에 맞게 한국어·일본어 본문을 확인했습니다.</span></label>
        <div className="flex flex-wrap gap-3"><button className={primaryButton} disabled={busy||uncertain||!publicChecked||!item.ready}>재분류 적용</button><button type="button" className={secondaryButton} disabled={busy||uncertain} onClick={()=>{setPublicOpened(false);setError('');}}>적용 취소</button></div>
      </form>}
    </section>}
    {(error||notice)&&<p role={error?'alert':'status'} className={error?reviewError:"mt-4 leading-7"}>{error||notice}</p>}
    {error&&(opened||publicOpened)&&<button type="button" className={`${secondaryButton} mt-3`} disabled={busy} onClick={()=>void read()}>입력을 유지하고 저장 상태 확인</button>}
  </section>;
}
