'use client';
import {useEffect,useRef,useState} from 'react';
import type {ReactNode} from 'react';
import type {Category,Facts,CandidateContent} from '@/app/lib/review/contracts';
import {ReviewFailure} from '@/app/lib/review/contracts';
import {classificationCategories,classificationCommand,classificationDetail,classificationFields,classificationFilterFacts,classificationMissing,classificationMatches,classificationApplyCommand,classificationSelection,classificationConfirmationNote} from '@/app/lib/review/classification';
import type {ClassificationDetail} from '@/app/lib/review/classification';
import {parseContentFilters} from '@/app/lib/contentFilters';
import type {ContentFilters,FilterKey} from '@/app/lib/contentFilters';
import {categories,failureText,reasonText} from '@/app/lib/review/presentation';
import {factLabels,factValue,visibleFactFields} from '@/app/lib/review/facts-guidance';
import {FactsEditor,CandidateEditor,fieldClass,primaryButton,secondaryButton} from './ReviewEditors';
import {reviewOverview,reviewError,reviewDirty,ReviewStatus,ReviewValueRow} from './ReviewStates';
import {FilterInputs,reviewFilterLabel,filterValueLabel} from './FilterReviewPanel';

async function request(id:string,body?:unknown,signal?:AbortSignal) {
  const r=await fetch(`/api/admin/review-classification/${id}`,{cache:'no-store',credentials:'same-origin',signal,...(body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});
  const b=await r.json().catch(()=>null);
  if(!r.ok)throw new ReviewFailure(b?.code??'unavailable',b?.fields);
  return classificationDetail(b?.item,id);
}
function initialDraft(item:ClassificationDetail) {
  return !item.active&&item.category?classificationSelection(item,item.facts,item.filters,item.category):{facts:item.facts,filters:item.filters};
}
export default function ClassificationPanel({id,disabled,onBlocked,onActive,onSaved,reference,overview}:{id:string;disabled:boolean;onBlocked:(v:boolean)=>void;onActive:(v:boolean)=>void;onSaved?:()=>Promise<void>;reference?:ReactNode;overview?:ReactNode}) {
  const[item,setItem]=useState<ClassificationDetail|null>(null),[facts,setFacts]=useState<Facts|null>(null),[filters,setFilters]=useState<ContentFilters|null>(null);
  const[opened,setOpened]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[note,setNote]=useState('');
  const[errors,setErrors]=useState<Record<string,string>>({}),[pending,setPending]=useState(false),[uncertain,setUncertain]=useState(false);
  const[editing,setEditing]=useState<string[]>([]);
  const[editorKey,setEditorKey]=useState(0),[checked,setChecked]=useState(false);
  const sending=useRef(false),region=useRef<HTMLElement>(null);
  const attempted=useRef<ReturnType<typeof classificationCommand>|null>(null);
  const drafts=useRef<Partial<Record<Category,{facts:Facts;filters:ContentFilters|null}>>>({});
  const appliedAttempt=useRef<ReturnType<typeof classificationApplyCommand>|null>(null);
  const[publicOpened,setPublicOpened]=useState(false),[publicContent,setPublicContent]=useState<CandidateContent|null>(null),[publicChecked,setPublicChecked]=useState(false),[publicNote,setPublicNote]=useState('');
  const[rowEdit,setRowEdit]=useState<{key:string;facts:Facts;filters:ContentFilters|null;version:string;pending:boolean;error:string}|null>(null);
  const rowEditKey=rowEdit?.key;
  const rowEditing=rowEdit!==null;
  const dirty=Boolean(opened&&item&&(JSON.stringify(facts)!==JSON.stringify(item.facts)||JSON.stringify(filters)!==JSON.stringify(item.filters)||note!==item.note||pending));
  useEffect(()=>{const c=new AbortController();request(id,undefined,c.signal).then(next=>{if(c.signal.aborted)return;const selected=initialDraft(next);setItem(next);setFacts(selected.facts);setFilters(selected.filters);setNote(next.note);if(!next.category)setOpened(true);onActive(next.active);}).catch(e=>{if(!c.signal.aborted)setError(failureText[e.code]??'분류 상태를 불러오지 못했습니다.');});return()=>c.abort();},[id,onActive]);
  useEffect(()=>{onBlocked(busy||opened||publicOpened);return()=>onBlocked(false);},[busy,opened,publicOpened,onBlocked]);
  useEffect(()=>{onActive(Boolean(item?.active||opened));},[item?.active,opened,onActive]);
  useEffect(()=>{if(!dirty&&!publicOpened&&!rowEditing)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty,publicOpened,rowEditing]);
  useEffect(()=>{if(rowEditKey)region.current?.querySelector<HTMLElement>(`[data-classification-row="${rowEditKey}"]`)?.querySelector<HTMLElement>('input,select,textarea')?.focus();},[rowEditKey]);
  function accept(next:ClassificationDetail){const selected=initialDraft(next);setItem(next);setFacts(selected.facts);setFilters(selected.filters);setNote(next.note);setPending(false);setUncertain(false);setChecked(false);setEditing([]);setRowEdit(null);setEditorKey(k=>k+1);drafts.current={};onActive(next.active);}
  async function read(){if(sending.current)return;setBusy(true);try{const next=await request(id);const sent=attempted.current;
    if(uncertain&&appliedAttempt.current&&next.publication?.applied&&next.classificationVersion===appliedAttempt.current.classificationVersion&&JSON.stringify(next.publication.content)===JSON.stringify(appliedAttempt.current.content)){accept(next);setPublicOpened(false);setError('');setNotice('읽기 확인으로 이전 공개 재분류 적용 완료를 확인했습니다. 다시 쓰지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('읽기 확인으로 저장 완료를 확인했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}
    else if(uncertain&&sent&&classificationMatches(next,sent)){accept(next);setOpened(false);setError('');setNotice('읽기 확인으로 이전 분류 저장 완료를 확인했습니다. 새 저장·AI 실행은 하지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('읽기 확인으로 저장 완료를 확인했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}
    else{setItem(next);onActive(next.active);setChecked(false);setPublicChecked(false);setNotice('현재 저장 상태를 확인했습니다. 입력은 유지했습니다. 최신 저장값과 보존한 입력을 다시 대조하세요. 확인 체크는 해제했습니다. 최신 저장값을 사용하려면 입력 취소를 선택하세요.');}
  }catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'상태 확인 실패':'상태 확인 실패');}finally{setBusy(false);}}
  if(!item||!facts)return <section className="my-5" aria-label="분류 변경">{error&&<p role="alert" className="text-info-status">{error}</p>}{overview}{reference}</section>;
  const missing=[...new Set(classificationMissing(facts,filters).map(k=>filters&&facts.category==='program'&&k==='delivery'?'filter:delivery':filters&&facts.category==='program'&&['deadlineKind','deadlineOn'].includes(k)?'filter:application':filters&&facts.category==='event'&&['eventStart','eventEnd'].includes(k)?'filter:schedule':k))];
  const editableFacts=(Object.keys(facts) as (keyof Facts)[]).filter(k=>k!=='category'&&(missing.includes(k)||editing.includes(k)||k==='regions'&&(missing.includes('scope')||editing.includes('scope'))||k==='deadlineOn'&&(missing.includes('deadlineKind')||editing.includes('deadlineKind')))&&!(facts.category==='program'&&['delivery','deadlineKind','deadlineOn'].includes(k))&&!(facts.category==='event'&&['eventStart','eventEnd'].includes(k)));
  const label=(k:string)=>k.startsWith('filter:')&&filters?reviewFilterLabel(filters,k.slice(7) as ReturnType<typeof classificationFields>[number]):factLabels[k as keyof Facts]??k;
  function jump(k:string){const node=region.current?.querySelector<HTMLElement>(k.startsWith('filter:')?`[data-filter-key="${k.slice(7)}"]`:`[id="classification-${k}"]`);if(!node){const details=region.current?.querySelector<HTMLDetailsElement>('[data-preserved-values]');if(details)details.open=true;openRow(k);return;}const control=node.matches('input,select,textarea')?node:node.querySelector<HTMLElement>('input,select,textarea,button');(control??node).focus();node.scrollIntoView({block:'center'});}
  const baseline=classificationSelection(item,item.facts,item.filters,facts.category);
  const originalMissing=classificationMissing(baseline.facts,baseline.filters);
  const initialFactNeeds=(key:keyof Facts)=>originalMissing.includes(key)||key==='regions'&&originalMissing.includes('scope')||key==='deadlineOn'&&originalMissing.includes('deadlineKind');
  function openRow(key:string){setRowEdit({key,facts:structuredClone(facts!),filters:structuredClone(filters),version:item!.version,pending:false,error:''});setChecked(false);}
  function closeRow(key:string){setRowEdit(null);const restore=()=>region.current?.querySelector<HTMLButtonElement>(`[data-classification-edit="${key}"]`)?.focus();if(typeof requestAnimationFrame==='function')requestAnimationFrame(restore);else restore();}
  function rowEditor(key:string){if(rowEdit?.key!==key)return null;const stale=rowEdit.version!==item!.version;const locked=busy||uncertain||stale;return <div role="group" aria-label={`${label(key)} 편집`} data-classification-row={key} className="space-y-4" onKeyDown={e=>{if(e.key==='Escape'&&!busy){e.preventDefault();e.stopPropagation();closeRow(key);}}}>
    {key.startsWith('filter:')&&rowEdit.filters?<FilterInputs data={rowEdit.filters} fields={[key.slice(7) as FilterKey]} onChange={v=>setRowEdit({...rowEdit,filters:v,facts:classificationFilterFacts(rowEdit.facts,v)})} disabled={locked} missing={[]} prefix="classification-row" onPending={v=>setRowEdit(current=>current?{...current,pending:v}:current)}/>:<FactsEditor idPrefix="classification-row-" value={rowEdit.facts} onChange={v=>setRowEdit({...rowEdit,facts:v})} errors={{}} disabled={locked} editableFields={[key as keyof Facts,...(key==='scope'?['regions' as const]:key==='deadlineKind'?['deadlineOn' as const]:[])]}/>}
    {stale&&<p role="alert" className="text-info-status">저장 버전이 변경됐습니다. 입력은 보존했습니다. 취소 후 최신 값을 확인해 주세요.</p>}{rowEdit.error&&<p role="alert" className="text-info-status">{rowEdit.error}</p>}
    <div className="flex flex-wrap gap-3"><button type="button" className={primaryButton} disabled={locked||rowEdit.pending} onClick={()=>{try{const invalid=region.current?.querySelector<HTMLElement>(`[data-classification-row="${key}"]`)?.querySelector<HTMLInputElement>('input:invalid,select:invalid');if(invalid){invalid.reportValidity();throw Error('invalid');}const next=rowEdit.filters?parseContentFilters(rowEdit.filters):null;setFacts(rowEdit.facts);setFilters(next);setEditing(keys=>[...new Set([...keys,key])]);setChecked(false);closeRow(key);}catch{setRowEdit({...rowEdit,error:'선택값·지역·날짜 형식을 확인해 주세요. 입력은 유지합니다.'});}}}>초안에 적용</button><button type="button" className={secondaryButton} disabled={busy} onClick={()=>closeRow(key)}>취소</button></div><p className="text-sm text-info-muted">아직 저장하지 않습니다. 취소하면 이번 행의 편집만 취소합니다.</p>
  </div>;}
  return <section ref={region} className="my-6 border-b border-info-rule pb-6" aria-label="공통 카테고리 검토" aria-busy={busy}>
    <div className="flex flex-wrap items-center justify-between gap-3"><p className="font-semibold">카테고리: {item.category?categories[item.category]:'분류 확인 필요'}</p><button type="button" className={secondaryButton} disabled={disabled||busy||publicOpened||rowEditing||!item.editable||opened&&dirty} onClick={()=>{setOpened(v=>!v);setError('');appliedAttempt.current=null;}}>{opened?'분류 변경 닫기':item.active?'분류·필수값 다시 확인':'분류 변경'}</button></div>
    {!item.editable&&<p className="mt-2 text-sm text-info-muted">처리 중이거나 제외된 항목입니다. 기존 처리 상태를 먼저 확인해 주세요.</p>}
    {item.active&&!opened&&<p className="mt-3 leading-7 text-info-body">{item.ready?'새 분류의 사실·필터 확인을 마쳤습니다. 후보 처리는 별도 실행입니다.':'새 분류에 남은 확인사항이 있습니다. 분류·필수값을 다시 확인해 주세요.'}</p>}
    {opened&&<div className="mt-5 space-y-6">
      <label className="block font-semibold">새 카테고리<select id="classification-category" className={fieldClass} value={facts.category} disabled={busy||uncertain||rowEdit!==null} form={`classification-form-${id}`} required onChange={e=>{const cat=e.target.value as Category;drafts.current[facts.category]={facts:structuredClone(facts),filters:structuredClone(filters)};const restored=drafts.current[cat];const next=restored?structuredClone(restored):classificationSelection(item,facts,filters,cat);setFacts(next.facts);setFilters(next.filters);setEditing([]);setPending(false);setEditorKey(k=>k+1);setChecked(false);}}><option value="" disabled>선택해 주세요</option>{classificationCategories.map(c=><option key={c} value={c}>{categories[c]}</option>)}</select></label>
      <section className={reviewOverview} aria-label="재분류 확인사항"><h3 className="font-bold">이번에 확인할 사항 · {missing.length}개</h3><p className="mt-2 text-sm leading-6">기존 값은 유지하고 부족한 항목만 표시합니다. 분류별 작성 중인 입력도 보존합니다. 신청 기간과 행사 일정은 서로 바꾸지 않습니다.</p>
        {missing.length?<ul className="mt-3 flex flex-wrap gap-x-4 gap-y-2">{missing.map(k=><li key={k}><button type="button" disabled={busy||uncertain||rowEditing} className="min-h-11 py-2 font-semibold underline underline-offset-4 disabled:opacity-45" onClick={()=>jump(k)}>{label(k)} · 확인 필요</button></li>)}</ul>:<p className="mt-3">필수 입력이 채워졌습니다. 저장 전 원문 근거를 확인해 주세요.</p>}
        {item.sourceReasons.length>0&&<p className="mt-3 text-sm leading-6">별도 사실 확인: {item.sourceReasons.map(r=>reasonText(r).title).join(' · ')}. 기존 사실 검토에서 확인하며, 분류 변경으로 자동 해소하지 않습니다.</p>}
      </section>
    </div>}
    {!opened&&overview}
    <div key="review-reference">{reference}</div>
    {opened&&<form id={`classification-form-${id}`} className="mt-5 space-y-6" onSubmit={async e=>{e.preventDefault();if(sending.current||disabled||pending||uncertain||rowEdit)return;setError('');setErrors({});let body;try{body=classificationCommand({revision:item.revision,version:item.version,classificationVersion:item.classificationVersion,facts,filters,note:classificationConfirmationNote(facts.category,note)});}catch(e){setError('새 분류의 필수값과 원문 근거를 확인해 주세요. 입력은 유지합니다.');if(e instanceof ReviewFailure)setErrors(e.fields);return;}if(!checked){setError('유지할 값과 다시 확인한 값을 검토한 뒤 확인 체크를 선택해 주세요.');return;}attempted.current=body;appliedAttempt.current=null;sending.current=true;setBusy(true);try{const next=await request(id,body);accept(next);setOpened(false);if(onSaved){try{await onSaved();}catch{setNotice("분류 저장은 완료했지만 기존 검토 상태를 새로 읽지 못했습니다. 최신 상태를 다시 확인해 주세요.");return;}}setNotice(next.ready?'분류와 필수값을 함께 저장·재판정했습니다. AI는 실행하지 않았습니다.':'분류를 저장했습니다. 남은 사실 확인을 마쳐야 후보 처리가 가능합니다.');}catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'저장 결과를 확인하지 못했습니다.':'저장 결과를 확인하지 못했습니다.');if(!(e instanceof ReviewFailure)||e.code==='unavailable')setUncertain(true);}finally{sending.current=false;setBusy(false);}}}>
      {filters&&<FilterInputs key={editorKey} data={filters} fields={classificationFields(facts.category).filter(k=>(missing.includes(`filter:${k}`)||editing.includes(`filter:${k}`))&&(!baseline.filters||classificationMissing(baseline.facts,baseline.filters).includes(`filter:${k}`)))} onChange={v=>{setEditing(keys=>[...new Set([...keys,...classificationFields(facts.category).filter(k=>JSON.stringify(filters[k])!==JSON.stringify(v[k])).map(k=>`filter:${k}`)])]);setFilters(v);setFacts(classificationFilterFacts(facts,v));setChecked(false);}} disabled={busy||uncertain||rowEdit!==null} onPending={setPending} missing={missing.filter(k=>k.startsWith('filter:')).map(k=>k.slice(7))} saved={item.filters??undefined} prefix="classification" confirmed={item.active&&facts.category===item.category?classificationFields(item.category).filter(k=>(item.filters?.[k].status==='known'||item.filters?.[k].status==='not_applicable')&&!classificationMissing(item.facts,item.filters).includes(`filter:${k}`)):[]}/>}
      {editableFacts.filter(initialFactNeeds).length>0&&<FactsEditor idPrefix="classification-" value={facts} onChange={v=>{setEditing(keys=>[...new Set([...keys,...Object.keys(v).filter(k=>JSON.stringify(facts[k as keyof Facts])!==JSON.stringify(v[k as keyof Facts]))])]);setFacts(v);setChecked(false);}} errors={errors} disabled={busy||uncertain||rowEdit!==null} missing={missing} saved={item.facts} confirmed={item.active&&facts.category===item.category} editableFields={editableFacts.filter(initialFactNeeds)}/>}
      <details data-preserved-values className="border-y border-info-rule py-4" onToggle={e=>{if(rowEdit&&!e.currentTarget.open)e.currentTarget.open=true;}}><summary className="min-h-11 cursor-pointer font-semibold">유지한 값 확인·수정</summary>
        <p className="mt-2 text-sm leading-6 text-info-muted">저장된 분류값과 분류별 초기값을 구분합니다. 초기값은 기존 사실·필터를 바탕으로 준비한 초안이며 확인 완료를 뜻하지 않습니다.</p>
        <dl>{filters&&classificationFields(facts.category).filter(k=>!classificationMissing(baseline.facts,baseline.filters).includes(`filter:${k}`)).map(k=>{const original=baseline.filters??filters;const changed=JSON.stringify(original[k])!==JSON.stringify(filters[k]);const saved=item.active&&facts.category===item.category;return <ReviewValueRow key={k} label={reviewFilterLabel(filters,k)} value={filterValueLabel(original,k)} origin={saved?'저장된 분류값':'분류별 초기값'} changedValue={changed?filterValueLabel(filters,k):undefined} status={saved||changed||missing.includes(`filter:${k}`)?<ReviewStatus needed={missing.includes(`filter:${k}`)} confirmed={saved&&!missing.includes(`filter:${k}`)} changed={changed}/>:null} action={<button type="button" data-classification-edit={`filter:${k}`} aria-label={`${reviewFilterLabel(filters,k)} 수정`} className={secondaryButton} disabled={busy||uncertain||rowEdit!==null} onClick={()=>openRow(`filter:${k}`)}>수정</button>}>{rowEditor(`filter:${k}`)}</ReviewValueRow>;})}
        {visibleFactFields(facts).filter(k=>k!=='category'&&!classificationMissing(baseline.facts,baseline.filters).includes(k)&&baseline.facts[k]!==''&&baseline.facts[k]!=='unknown'&&!(facts.category==='program'&&['delivery','deadlineKind','deadlineOn'].includes(k))&&!(facts.category==='event'&&['eventStart','eventEnd'].includes(k))).map(k=>{const changed=JSON.stringify(baseline.facts[k])!==JSON.stringify(facts[k]);return <ReviewValueRow key={k} label={factLabels[k]} value={factValue(baseline.facts,k)} origin={item.active&&facts.category===item.category?'저장된 분류값':'분류별 초기값'} changedValue={changed?factValue(facts,k):undefined} status={item.active&&facts.category===item.category||changed||missing.includes(k)?<ReviewStatus needed={missing.includes(k)} confirmed={item.active&&facts.category===item.category&&!missing.includes(k)} changed={changed}/>:null} action={<button type="button" data-classification-edit={k} aria-label={`${factLabels[k]} 수정`} className={secondaryButton} disabled={busy||uncertain||rowEdit!==null} onClick={()=>openRow(k)}>수정</button>}>{rowEditor(k)}</ReviewValueRow>;})}</dl>
        {note&&<p className="mt-3 whitespace-pre-wrap text-sm leading-6">기존 분류 검토 기록: {note}</p>}
      </details>
      <label className="flex min-h-11 items-start gap-3"><input type="checkbox" className="mt-1 size-5 accent-ink" checked={checked} disabled={busy||uncertain||rowEditing} onChange={e=>setChecked(e.target.checked)}/><span>유지할 값과 새 분류의 필수값·원문 근거를 확인했습니다.</span></label>
      {dirty&&<p className={reviewDirty}>미저장 변경이 있습니다.</p>}
      <div className="flex flex-wrap gap-3"><button type="submit" className={primaryButton} disabled={busy||uncertain||pending||rowEdit!==null}>{busy?'저장 중…':'분류·필수값 저장·재판정'}</button><button type="button" className={secondaryButton} disabled={busy||rowEdit!==null} onClick={()=>{accept(item);setOpened(false);setError('');}}>입력 취소</button></div>
    </form>}
    {item.publication&&<section className="mt-5 border-t border-info-rule pt-5" aria-label="공개 콘텐츠 재분류 적용">
      <p className="font-semibold">현재 공개 분류: {item.publication.category?categories[item.publication.category]:"분류 확인 필요"}</p>
      <p className="mt-2 leading-7">검토 중에는 기존 공개본을 유지합니다. 새 분류와 한국어·일본어 본문을 확인한 뒤 명시적으로 적용합니다. 콘텐츠 ID·URL·저장·댓글은 유지합니다. AI는 실행하지 않습니다.</p>
      {!publicOpened&&<button type="button" className={`${secondaryButton} mt-3`} disabled={disabled||busy||opened||!item.active||!item.ready||item.publication.applied} onClick={()=>{setPublicContent(structuredClone(item.publication!.content));setPublicNote('');setPublicChecked(false);setPublicOpened(true);setError('');attempted.current=null;appliedAttempt.current=null;}}>{item.publication.applied?'현재 분류 적용 완료':'공개 본문 확인·재분류 적용'}</button>}
      {publicOpened&&publicContent&&<form className="mt-5 space-y-5" onSubmit={async e=>{e.preventDefault();if(sending.current||disabled||uncertain||!publicChecked)return;let body;try{body=classificationApplyCommand({action:'apply_public',revision:item.revision,version:item.version,classificationVersion:item.classificationVersion,publicationVersion:item.publication!.version,content:publicContent,bodyReviewed:publicChecked,note:publicNote});}catch{setError('두 언어의 본문과 적용 근거를 확인해 주세요. 입력은 유지합니다.');return;}appliedAttempt.current=body;sending.current=true;setBusy(true);setError('');try{const next=await request(id,body);accept(next);setPublicOpened(false);setNotice('공개 카테고리·필터·확인한 본문을 함께 적용했습니다. AI를 실행하지 않았습니다.');if(onSaved){try{await onSaved();}catch{setNotice('공개 재분류 적용은 완료했지만 기존 검토 화면을 갱신하지 못했습니다. 화면을 다시 확인해 주세요.');}}}catch(e){setError(e instanceof ReviewFailure?failureText[e.code]??'적용 결과를 확인하지 못했습니다.':'적용 결과를 확인하지 못했습니다.');if(!(e instanceof ReviewFailure)||e.code==='unavailable')setUncertain(true);}finally{sending.current=false;setBusy(false);}}}>
        <p className={reviewOverview}>적용할 분류: <strong>{item.category?categories[item.category]:"분류 확인 필요"}</strong> · 필요한 본문 수정도 이 적용 요청에서 함께 저장됩니다.</p>
        {JSON.stringify(publicContent)!==JSON.stringify(item.publication.content)&&<details className="border-y border-info-rule py-3"><summary className="min-h-11 cursor-pointer font-semibold">현재 공개본과 수정 입력 대조</summary><p className="my-3">아래는 현재 공개된 저장본이며 작성 중인 입력은 다음 편집란에 보존합니다. 다른 검토자의 변경을 덮어쓰지 않도록 대조 후 다시 확인하세요.</p>{Object.entries(item.publication.content).map(([k,v])=><div key={k} className="mb-4"><p className="font-semibold">{({titleKo:'한국어 제목',summaryKo:'한국어 요약',contentKo:'한국어 본문',titleJa:'일본어 제목',summaryJa:'일본어 요약',contentJa:'일본어 본문'} as Record<string,string>)[k]}</p><p className="whitespace-pre-wrap break-words">{v||'비어 있음'}</p></div>)}</details>}
        <CandidateEditor value={publicContent} onChange={v=>{setPublicContent(v);setPublicChecked(false);}} errors={{}} disabled={busy||uncertain}/>
        <label className="block font-semibold">공개 적용 근거<textarea className={fieldClass} minLength={10} maxLength={4000} required rows={3} value={publicNote} disabled={busy||uncertain} onChange={e=>{setPublicNote(e.target.value);setPublicChecked(false);}}/></label>
        <label className="flex min-h-11 items-start gap-3"><input type="checkbox" checked={publicChecked} disabled={busy||uncertain} onChange={e=>setPublicChecked(e.target.checked)}/><span>새 분류와 필터에 맞게 한국어·일본어 본문을 확인했습니다.</span></label>
        <div className="flex flex-wrap gap-3"><button className={primaryButton} disabled={busy||uncertain||!publicChecked||!item.ready}>재분류 적용</button><button type="button" className={secondaryButton} disabled={busy||uncertain} onClick={()=>{setPublicOpened(false);setError('');}}>적용 취소</button></div>
      </form>}
    </section>}
    {(error||notice)&&<p role={error?'alert':'status'} className={error?reviewError:"mt-4 leading-7"}>{error||notice}</p>}
    {error&&(opened||publicOpened)&&<button type="button" className={`${secondaryButton} mt-3`} disabled={busy} onClick={()=>void read()}>입력을 유지하고 저장 상태 확인</button>}
  </section>;
}
