import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';
import { registerHooks } from 'node:module';
import ts from 'typescript';
import React from 'react';
import { renderToStaticMarkup } from 'react-dom/server';

// No credentials or external reads. Fake query/client hooks are confined to this test.
globalThis.fetch = () => { throw Error('external_network_forbidden'); };
const root=path.resolve('.'), moduleUrl=s=>`data:text/javascript,${encodeURIComponent(s)}`;
const mocks={
  'next/navigation':moduleUrl(`export function useSearchParams(){return new URLSearchParams(globalThis.testParams||'')} export function notFound(){throw Error('not_found')}`),
  'next-intl':moduleUrl(`export function useLocale(){return globalThis.testLocale||'ko'} export function useTranslations(namespace){return (key,args={})=>{let text=globalThis.testMessages[namespace];for(const part of key.split('.'))text=text?.[part];if(typeof text!=='string')throw Error('missing_translation:'+namespace+'.'+key);return text.replace(/\\{(\\w+)\\}/g,(_,k)=>String(args[k]))}}`),
  'next-intl/server':moduleUrl('export function setRequestLocale(){}'),
  '@/app/lib/supabase':moduleUrl(`const query={select(...args){globalThis.queryCalls.push(['select',...args]);return this},eq(...args){globalThis.queryCalls.push(['eq',...args]);return this},order(...args){globalThis.queryCalls.push(['order',...args]);return this},maybeSingle(){return this},then(resolve,reject){return Promise.resolve(globalThis.queryResponse).then(resolve,reject)}};export const supabase={from(name){globalThis.queryCalls.push(['from',name]);return query}}`),
  '@/i18n/routing':moduleUrl(`export const routing={locales:['ko','ja']}`),
  'next/image':moduleUrl(`import React from 'react';export default function Image({alt,src,...props}){delete props.fill;delete props.priority;delete props.unoptimized;return React.createElement('img',{alt,src,...props})}`),
};
const linkMock=moduleUrl(`import React from 'react';export default function Link({href,children,feedback,...props}){return React.createElement('a',{...props,href},children)}`);
registerHooks({
  resolve(specifier,context,next){
    if(context.parentURL?.startsWith('data:') && specifier==='react')return next(specifier,{...context,parentURL:import.meta.url});
    if(mocks[specifier])return {url:mocks[specifier],shortCircuit:true};
    if(specifier.includes('PublicNavigationLink'))return {url:linkMock,shortCircuit:true};
    if(specifier.startsWith('@/'))specifier=pathToFileURL(path.join(root,specifier.slice(2))).href;
    try{return next(specifier,context)}catch(error){if(specifier.startsWith('.')||specifier.startsWith('file:'))for(const suffix of ['.ts','.tsx'])try{return next(specifier+suffix,context)}catch{}throw error}
  },
  load(url,context,next){
    if(url.endsWith('.css'))return {format:'module',source:'export default new Proxy({}, {get:(_,k)=>k})',shortCircuit:true};
    if(url.endsWith('.tsx'))return {format:'module',source:ts.transpileModule(fs.readFileSync(fileURLToPath(url),'utf8'),{compilerOptions:{module:ts.ModuleKind.ESNext,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText,shortCircuit:true};
    return next(url,context);
  },
});
const filters=await import('../app/lib/contentFilters.ts');
const f=await import('../app/lib/publicContentFilters.ts');
const {localizeCuration,fetchLocalizedCurations,publicCurationColumns}=await import('../app/lib/curations.ts');
const {default:List}=await import('../app/components/PublicCurationList.tsx');
const {default:Explorer}=await import('../app/components/CurationExplorer.tsx');
const selectedTest=process.argv[2]?new RegExp(process.argv[2]):null;
let passed=0;function test(name,run){if(selectedTest&&!selectedTest.test(name))return;run();passed++;console.log('PASS',name)}
const now=Date.parse('2026-10-08T12:00:00+09:00'), unknown={status:'unknown',value:null}, na={status:'not_applicable',value:null};
const known=value=>({status:'known',value}), endpoint=(value,precision='day')=>({value,precision});
const venue=(province='11',district='강남구')=>({province,district,facility:'합성 공간',address:'합성 주소'});
const location=(venues=[venue()])=>known({scope:'specific',venues});
function program(id='p',patch={}){return item(id,'program',{...filters.emptyContentFilters('program'),topic:known('language_learning'),delivery:known('onsite'),audience:known('other'),location:location(),application:known({deadlineKind:'fixed',start:endpoint('2026-10-01'),end:endpoint('2026-10-10'),sourceStatus:'open'}),...patch})}
function event(id='e',pairs=[['2026-10-10','2026-10-10']],patch={}){return item(id,'event',{...filters.emptyContentFilters('event'),topic:known('culture_arts'),location:location(),schedule:known({kind:pairs.length===1?'continuous':'occurrences',occurrences:pairs.map(([start,end])=>({start:endpoint(start),end:endpoint(end)})),recurrence:null}),...patch})}
function space(id='s',kind='introduction',patch={}){return item(id,'youth_space',{...filters.emptyContentFilters('youth_space'),spaceKind:known(kind),location:kind==='introduction'?location():na,...patch})}
function item(id,category,data=null){return {id,slug:id,userCategory:category,title:'합성 콘텐츠 '+id,summary:'검증을 위한 합성 요약입니다.',source_image_url:null,application_deadline_kind:null,application_deadline_on:null,event_start_on:null,event_end_on:null,created_at:'2026-10-01T00:00:00Z',contentFilters:data}}
const query=(s='',cat='program')=>f.readExplorationQuery(new URLSearchParams(s),cat), match=(i,s,cat=i.userCategory)=>f.matchesExploration(i,query(s,cat),now);
test('known topics OR and different conditions AND',()=>{const i=program();assert(match(i,'topic=culture_experience&topic=language_learning&audience=other'));assert(!match(i,'topic=language_learning&audience=children'));});
test('unknown, not_applicable and other stay distinct',()=>{assert(!match(program('p',{topic:unknown}),'topic=other'));assert(match(program('p',{topic:known('other')}),'topic=other'));assert(!match(program('p',{audience:unknown}),'audience=other'));});
test('legacy remains unfiltered; only selected unknowns exclude',()=>{assert(match(item('old','program'),''));assert(!match(item('old','program'),'region=11'));assert(match(program('p',{audience:unknown}),'topic=language_learning'));});
test('upper region and lower region facts are distinct',()=>{assert(match(program('p',{location:location([venue('11',null)])}),'region=11'));assert(!match(program('p',{location:location([venue('11',null)])}),'region=11&district=11:강남구'));});
test('multiple venues and regions OR; district belongs to its province',()=>{const i=program('p',{location:location([venue('41','수원시'),venue('11','강남구')])});assert(match(i,'region=11&district=11:강남구'));assert(match(i,'region=11&district=11:송파구&region=41'));assert(!match(i,'region=11&district=11:송파구'));});
test('online exception only bypasses region',()=>{const i=program('p',{delivery:known('online'),location:na});assert(match(i,'region=28&district=28:연수구'));assert(!match(i,'region=28&topic=employment_career'));});
test('mixed delivery uses the physical venue',()=>{assert(!match(program('p',{delivery:known('mixed')}),'region=28'));});
test('nationwide use is a region exception; unrelated text is not',()=>{assert(match(program('p',{location:known({scope:'nationwide',venues:[]})}),'region=28'));assert(!match({...program(),summary:'전국 신청 가능'},'region=28'));});
test('URL validates category values and drops invalid districts',()=>{const q=query('topic=nope&topic=other&region=11&district=41:수원시&district=11:강남구&delivery=onsite&date=2026-02-30');assert.deepEqual(q.topics,['other']);assert.deepEqual(q.districts,['11:강남구']);assert.equal(q.date,'');assert.deepEqual(query('delivery=online&status=open','event').deliveries,[]);});
test('URL keeps unrelated search; resets pagination and stale subregions',()=>{const q=query('region=11&district=11:강남구');q.provinces=['41'];const p=f.writeExplorationQuery(new URLSearchParams('q=preserved&page=3'),q,'program');assert.equal(p.get('q'),'preserved');assert(!p.has('page'));assert(!p.has('district'));});
test('empty reset keeps other search parameters',()=>{const p=f.writeExplorationQuery(new URLSearchParams('topic=other&q=x&sort=latest'),query(),'program');assert.equal(p.toString(),'q=x');});
test('space subtypes OR, news are not constrained by introduction region',()=>{const q='space=introduction&space=news&region=28';assert(match(space('news','news'),q,'youth_space'));assert(!match(space('intro'),q,'youth_space'));assert(!match(item('old','youth_space'),'space=news','youth_space'));});
test('space whole view includes unknown; news preserves dormant region',()=>{assert(match(item('old','youth_space'),'','youth_space'));const q=query('space=news&region=11&district=11:강남구','youth_space');assert.deepEqual(q.provinces,['11']);assert.deepEqual(q.districts,['11:강남구']);assert(match(space('news','news'),'space=news&region=11&district=11:강남구','youth_space'));});
test('connection audience both retains OR and excludes unknown',()=>{const list=[program('child',{audience:known('children')}),program('other'),item('unknown','program')];assert.deepEqual(f.exploreCurations(list,'program',query('audience=children&audience=other'),now).map(i=>i.id),['child','other']);assert.equal(f.exploreCurations(list,'program',query(),now).length,3);});
test('connection space tab URL reload and locale roundtrip preserves region',()=>{const intro=query('space=introduction&region=11&district=11:강남구','youth_space');const news=f.writeExplorationQuery(new URLSearchParams(),{...intro,spaceKinds:['news']},'youth_space');const reloaded=query(news.toString(),'youth_space');assert.deepEqual(reloaded.districts,intro.districts);const locale=f.writeExplorationQuery(new URLSearchParams(),reloaded,'youth_space');assert.equal(locale.toString(),news.toString());const restored={...query(locale.toString(),'youth_space'),spaceKinds:['introduction']};assert(f.matchesExploration(space('intro'),restored,now));assert(!f.matchesExploration(space('other','introduction',{location:location([venue('41','수원시')])}),restored,now));});
test('connection dormant region remains validated and reset keeps news tab',()=>{const q=query('space=news&region=11&district=41:수원시&district=11:강남구&region=invalid','youth_space');assert.deepEqual(q.provinces,['11']);assert.deepEqual(q.districts,['11:강남구']);const empty=query('','youth_space');const reset=f.writeExplorationQuery(new URLSearchParams('q=keep&page=3'),{...empty,spaceKinds:q.spaceKinds,sort:q.sort},'youth_space');assert.equal(reset.get('space'),'news');assert(!reset.has('region'));assert(!reset.has('district'));assert(!reset.has('page'));assert.equal(reset.get('q'),'keep');});
test('day deadline includes the complete KST deadline day',()=>{const i=program('p',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-08'),sourceStatus:'open'})});assert.equal(f.programTiming(i,Date.parse('2026-10-08T23:59:59.999+09:00')).state,'open');assert.equal(f.programTiming(i,Date.parse('2026-10-09T00:00:00+09:00')).state,'closed');});
test('minute deadline uses its real instant',()=>{const i=program('p',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-08T12:00:00+09:00','minute'),sourceStatus:'open'})});assert.equal(f.programTiming(i,now).state,'open');assert.equal(f.programTiming(i,now+1).state,'closed');});
test('second deadline and start boundary do not lose precision',()=>{const i=program('p',{application:known({deadlineKind:'fixed',start:endpoint('2026-10-08T12:00:05+09:00','second'),end:endpoint('2026-10-08T12:01:07+09:00','second'),sourceStatus:'not_started'})});assert.equal(f.programTiming(i,now).state,'not_started');assert.equal(f.programTiming(i,now+5000).state,'open');assert.equal(f.programTiming(i,now+67001).state,'closed');});
test('unknown reception and contradictory future start are not open',()=>{assert.equal(f.programTiming(program('p',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-10'),sourceStatus:'unknown'})}),now).state,'unknown');assert.equal(f.programTiming(program('p',{application:known({deadlineKind:'fixed',start:endpoint('2026-10-09'),end:endpoint('2026-10-10'),sourceStatus:'open'})}),now).state,'unknown');});
test('explicit closed remains closed before dated deadline',()=>{const i=program('p',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-10'),sourceStatus:'closed'})});assert(match(i,'status=closed'));assert.equal(f.programTiming(i,now).group,2);});
test('none is not unknown and is not inferred open',()=>{const none=program('n',{application:known({deadlineKind:'none',start:null,end:null,sourceStatus:'unknown'})});assert.equal(f.programTiming(none,now).deadlineKind,'none');assert.equal(f.programTiming(program('u',{application:unknown}),now).deadlineKind,'unknown');assert(!match(none,'status=open'));});
test('program ordering: dated future, unknown/none, closed recent first',()=>{const early=program('early',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-09'),sourceStatus:'not_started'})});const closed=program('closed',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-07'),sourceStatus:'closed'})});const older=program('older',{application:known({deadlineKind:'fixed',start:null,end:endpoint('2026-10-06'),sourceStatus:'closed'})});assert.deepEqual(f.exploreCurations([older,closed,item('unknown','program'),program('later'),early],'program',query(),now).map(i=>i.id),['early','later','unknown','closed','older']);});
test('published legacy dates work without inventing new metadata',()=>{const i={...item('legacy','program'),application_deadline_kind:'fixed',application_deadline_on:'2026-10-07'};assert.equal(f.programTiming(i,now).state,'closed');assert(match(i,'status=closed'));});
test('future legacy deadline can sort but cannot assert open reception',()=>{const i={...item('legacy','program'),application_deadline_kind:'fixed',application_deadline_on:'2026-10-10'};assert.equal(f.programTiming(i,now).group,0);assert.equal(f.programTiming(i,now).state,'unknown');assert(!match(i,'status=open'));});
test('new unknown application never takes legacy dates as its value',()=>{const i={...program('new',{application:unknown}),application_deadline_kind:'fixed',application_deadline_on:'2026-10-07'};assert.equal(f.programTiming(i,now).deadlineKind,'unknown');});
test('event phases use actual active and next intervals',()=>{const ongoing=event('ongoing',[['2026-10-08','2026-10-08'],['2026-10-15','2026-10-15']]);assert.equal(f.eventTiming(ongoing,now).state,'ongoing');const gap=event('gap',[['2026-10-03','2026-10-03'],['2026-10-10','2026-10-10']]);assert.equal(f.eventTiming(gap,now).state,'upcoming');assert.equal(f.eventTiming(gap,now).occurrence.start.value,'2026-10-10');});
test('date search does not fill gaps between occurrences',()=>{const i=event('gap',[['2026-10-03','2026-10-03'],['2026-10-10','2026-10-10']]);assert(match(i,'date=2026-10-10','event'));assert(!match(i,'date=2026-10-08','event'));});
test('continuous event includes boundary days but not adjacent days',()=>{const i=event('c',[['2026-10-08','2026-10-10']]);assert(match(i,'date=2026-10-10','event'));assert(!match(i,'date=2026-10-11','event'));});
test('finite recurring Saturdays and exceptions use stored occurrences',()=>{const rec={from:'2026-10-01',through:'2026-10-31',weekdays:[6],startTime:null,endTime:null,precision:'day',exceptions:['2026-10-17']};const expanded=filters.expandFilterRecurrence(rec);const i=event('r',[['2026-10-03','2026-10-03']],{schedule:known({kind:'occurrences',...expanded})});assert(match(i,'date=2026-10-10','event'));assert(!match(i,'date=2026-10-17','event'));assert(!match(i,'date=2026-10-08','event'));});
test('event minute intervals crossing KST midnight match both dates',()=>{const i=event('night',[['2026-10-08','2026-10-08']],{schedule:known({kind:'continuous',recurrence:null,occurrences:[{start:endpoint('2026-10-08T23:30:00+09:00','minute'),end:endpoint('2026-10-09T00:30:00+09:00','minute')}]})});assert(match(i,'date=2026-10-09','event'));assert.equal(f.eventTiming(i,Date.parse('2026-10-09T00:31:00+09:00')).state,'ended');});
test('event ordering uses ongoing end, next start, recent end, then unknown',()=>{const list=[item('unknown','event'),event('old',[['2026-10-01','2026-10-01']]),event('recent',[['2026-10-07','2026-10-07']]),event('next',[['2026-10-10','2026-10-10']]),event('long',[['2026-10-08','2026-10-12']]),event('short',[['2026-10-08','2026-10-08']])];assert.deepEqual(f.exploreCurations(list,'event',query('','event'),now).map(i=>i.id),['short','long','next','recent','old','unknown']);});
test('unknown event is not ended; existing published legacy date search works',()=>{assert.equal(f.eventTiming(item('unknown','event'),now).state,'unknown');assert(match({...item('legacy','event'),event_start_on:'2026-10-08',event_end_on:'2026-10-08'},'date=2026-10-08','event'));});
test('sorting is stable, deduplicates, and does not mutate inputs',()=>{const a=program('a'),b=program('b');const source=[b,a,a];const before=JSON.stringify(source);assert.deepEqual(f.exploreCurations(source,'program',query(),now).map(i=>i.id),['a','b']);assert.equal(JSON.stringify(source),before);});
test('clock refresh uses actual KST transition instead of polling inputs',()=>{const p=program('p',{application:known({deadlineKind:'fixed',start:endpoint('2026-10-09'),end:endpoint('2026-10-10'),sourceStatus:'not_started'})});assert.equal(f.nextExplorationTransition([p],now),Date.parse('2026-10-09T00:00:00+09:00'));assert.equal(f.nextExplorationTransition([event('e',[['2026-10-08','2026-10-08']])],now),Date.parse('2026-10-09T00:00:00+09:00'));assert.equal(f.nextExplorationTransition([item('old','program')],now),null);});
test('latest sorting and youth-space latest use published timestamp',()=>{const a=program('a'),b={...program('b'),created_at:'2026-10-02T00:00:00Z'};assert.equal(f.exploreCurations([a,b],'program',query('sort=latest'),now)[0].id,'b');assert.equal(f.exploreCurations([space('a'),{...space('b'),created_at:b.created_at}],'youth_space',query('','youth_space'),now)[0].id,'b');});
test('malformed dates and category mismatch do not create classification',()=>{assert.equal(query('date=2026-02-30','event').date,'');assert(!match({...program(),contentFilters:space().contentFilters},'topic=language_learning'));});
test('client projection never sends body/source/actor/history',()=>{const out=f.publicCurationItem({...program(),content:'private-sized-body',source_item_id:'not-required',history:['actor'],payload:{token:'secret'}});assert(!('content'in out));assert(!('history'in out));assert(!('source_item_id'in out));assert(!('payload'in out));});
const row={id:'row',slug:'row',category:'source-category',user_category:'program',title_ko:'합성 제목',title_ja:'合成タイトル',summary_ko:'합성 요약',summary_ja:'合成要約',content_ko:'합성 본문',content_ja:'合成本文',created_at:'2026-10-01T00:00:00Z',updated_at:'2026-10-01T00:00:00Z',content_filters:program().contentFilters};
test('public localization uses published filters and does not mutate snapshot',()=>{const before=JSON.stringify(row);assert.equal(localizeCuration(row,'ko').contentFilters.topic.value,'language_learning');assert.equal(localizeCuration(row,'ja').title,'合成タイトル');assert.equal(JSON.stringify(row),before);});
if(!selectedTest){
globalThis.queryCalls=[];globalThis.queryResponse={data:[row],error:null,count:1};await fetchLocalizedCurations('ko','program');test('published read is category-scoped and explicitly projected',()=>{assert(globalThis.queryCalls.some(c=>c[0]==='eq'&&c[1]==='is_published'&&c[2]===true));assert(globalThis.queryCalls.some(c=>c[0]==='eq'&&c[1]==='user_category'&&c[2]==='program'));assert(!publicCurationColumns.includes('*'));assert.deepEqual(globalThis.queryCalls.find(c=>c[0]==='select')[2],{count:'exact'});});
globalThis.queryResponse={data:[row],error:null,count:2};await assert.rejects(()=>fetchLocalizedCurations('ko'),/truncated/);passed++;console.log('PASS server row cap is not presented as whole results');
globalThis.queryResponse={data:null,error:{code:'failed'},count:null};await assert.rejects(()=>fetchLocalizedCurations('ko'),/Failed to load/);passed++;console.log('PASS failed reads are not shown as successful empty lists');
}
for(const locale of ['ko','ja']){
  globalThis.testLocale=locale;globalThis.testMessages=JSON.parse(fs.readFileSync(`messages/${locale}.json`,'utf8'));
  globalThis.testParams='region=11&district=11:강남구&topic=language_learning';
  test(locale+' SSR active chips, card link and title',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[program()],category:'program',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes(globalThis.testMessages.PublicFilters.selected+' (2)'));assert(html.includes('href="/info/p"'));assert(html.includes('aria-label='));assert(html.includes('합성 콘텐츠 p'));assert(!html.includes('missing_translation'));});
  globalThis.testParams='audience=children&audience=other';
  test(locale+' connection SSR audience both has one clear target and confirmed results',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[program('child',{audience:known('children')}),program('other'),item('unknown','program')],category:'program',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes(globalThis.testMessages.PublicFilters.audienceBoth));assert(html.includes(globalThis.testMessages.PublicFilters.selected+' (1)'));assert(html.includes('합성 콘텐츠 child'));assert(html.includes('합성 콘텐츠 other'));assert(!html.includes('합성 콘텐츠 unknown'));});
  globalThis.testParams='space=introduction&space=news&region=11';
  test(locale+' connection SSR space both retains results without selecting a misleading tab',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[space('intro'),space('news','news'),item('unknown','youth_space')],category:'youth_space',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes(globalThis.testMessages.PublicFilters.spaceBothHint));assert.equal((html.match(/aria-selected="false"/g)||[]).length,2);assert(html.includes('합성 콘텐츠 intro'));assert(html.includes('합성 콘텐츠 news'));assert(!html.includes('합성 콘텐츠 unknown'));});
  globalThis.testParams='space=introduction';
  test(locale+' connection space-empty distinguishes a filtered tab from no content',()=>{const props={category:'youth_space',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()};const filtered=renderToStaticMarkup(React.createElement(List,{...props,items:[item('unknown','youth_space')]}));assert(filtered.includes(globalThis.testMessages.Info.searchEmptyTitle));assert(!filtered.includes('합성 콘텐츠 unknown'));const empty=renderToStaticMarkup(React.createElement(List,{...props,items:[]}));assert(empty.includes(globalThis.testMessages.Info.emptyTitle));assert(!empty.includes(globalThis.testMessages.Info.searchEmptyTitle));});
  globalThis.testParams='topic=employment_career';
  test(locale+' filter-empty differs from genuinely empty content',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[program()],category:'program',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes(globalThis.testMessages.Info.searchEmptyTitle));assert(html.includes(globalThis.testMessages.PublicFilters.reset));});
  globalThis.testParams='';
  test(locale+' policy and living have no new filter UI',()=>{for(const category of ['policy','living']){const html=renderToStaticMarkup(React.createElement(Explorer,{curations:[{...row,...item('old',category)}],selectedCategory:category,todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(!html.includes(globalThis.testMessages.PublicFilters.conditions));}});
  test(locale+' no content shows genuine empty state',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[],category:'event',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes(globalThis.testMessages.Info.emptyTitle));assert(!html.includes(globalThis.testMessages.Info.searchEmptyTitle));});
  test(locale+' existing image and card destinations are preserved',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[{...program(),source_image_url:'https://global.seoul.go.kr/synthetic-poster.jpg'}],category:'program',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(html.includes('src="https://global.seoul.go.kr/synthetic-poster.jpg"'));assert(html.includes('referrerPolicy="no-referrer"'));assert.equal((html.match(/href="\/info\/p"/g)||[]).length,2);});
  globalThis.testParams='space=news';
  test(locale+' news has no empty region disclosure',()=>{const html=renderToStaticMarkup(React.createElement(List,{items:[space('n','news')],category:'youth_space',todayKst:'2026-10-08',nowIso:new Date(now).toISOString()}));assert(!html.includes('<details'));assert(html.includes(globalThis.testMessages.PublicFilters.spaceKinds.news));});
}
test('district translations cover exactly the existing service vocabulary',()=>{const ja=JSON.parse(fs.readFileSync('messages/ja.json','utf8'));for(const [p,ds]of Object.entries(filters.districtChoices))assert.deepEqual(Object.keys(ja.PublicFilters.districts[p]),ds);});
console.log(JSON.stringify({passed,external_requests:0}));
