// Actual contracts/handlers/components with fake Auth/RPC only. No env or network.
import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';import {execFileSync} from 'node:child_process';
const root=fileURLToPath(new URL('../',import.meta.url)),require=createRequire(import.meta.url),ts=require('typescript'),React=require('react');
let states=[],refs=[],cursor=0,refCursor=0;
const fakeReact={...React,useState(v){const i=cursor++;if(!(i in states))states[i]=typeof v==='function'?v():v;return[states[i],n=>states[i]=typeof n==='function'?n(states[i]):n];},useEffect(){},useRef(v){return refs[refCursor++]??={current:v};}};
const cache=new Map();function load(name){const file=path.resolve(root,name);if(cache.has(file))return cache.get(file);const out={};cache.set(file,out);new Function('require','exports',ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,jsx:ts.JsxEmit.ReactJSX,target:ts.ScriptTarget.ES2022}}).outputText)(s=>{if(s==='react')return fakeReact;if(s==='next/link')return{default:()=>null};if(s.startsWith('@/')||s.startsWith('.')){const p=s.startsWith('@/')?path.join(root,s.slice(2)):path.resolve(path.dirname(file),s);for(const ext of ['.ts','.tsx',''])if(fs.existsSync(p+ext))return load(path.relative(root,p+ext));}return require(s);},out);return out;}
const {myseoulCommand}=load('app/lib/review/myseoul-contract.ts'),{MySeoulReviewStore,myseoulItem}=load('app/lib/review/myseoul-store.ts'),{myseoulRequest}=load('app/lib/review/myseoul-handlers.ts'),{trashRequest}=load('app/lib/review/trash-handlers.ts'),{TrashStore}=load('app/lib/review/trash.ts');
const Residence=load('app/components/admin/MySeoulResidenceReview.tsx').default,Panel=load('app/components/admin/MySeoulReviewPanel.tsx').default;
const fixture=JSON.parse(execFileSync(process.env.MACHIMOA_TEST_PYTHON,['-X','utf8','test_myseoul_db.py','--fixtures'],{cwd:path.join(root,'scripts'),encoding:'utf8'})).fixtures.find(f=>f.name==='online');
const id='40000000-0000-4000-8000-000000000901',actor='00000000-0000-4000-8000-000000000001',rid='00000000-0000-4000-8000-000000000003';
const f={...fixture.item.myseoul_facts,residence_scope:'unknown',residence:'',residence_evidence:[]};
const raw={id,revision:f.source_revision,version:'b'.repeat(64),schema:f.schema_version,profile:'myseoul-program-v1-local',factsVersion:1,source:{name:'myseoul_program',title:'합성 온라인 검토',url:f.official_url,body:f.description},facts:f,observedFacts:structuredClone(f),status:'open',aiStatus:'blocked',result:{...fixture.expected,reasons:['online_residence_unknown'],decision:'review_required',disposition:'observe_only'},editableFields:['residence_scope','residence','residence_evidence'],history:[]};
const item=myseoulItem(raw,id);let count=0;const eq=(a,b)=>{assert.deepEqual(a,b);count++;},ok=a=>{assert.ok(a);count++;};
const c={action:'confirm_residence',revision:item.revision,version:item.version,restricted:false,scope:'',condition:'',evidence:[],requestId:rid};eq(myseoulCommand(c),c);
for(const bad of [{...c,actor},{...c,restricted:null},{...c,scope:'nationwide'},{...c,condition:'made up source'},{...c,evidence:['fake quote']},{...c,requestId:''},{...c,version:'bad'},{...c,restricted:true},{...c,restricted:true,scope:'noncapital_only',condition:'부산만',evidence:['부산만']}]){assert.throws(()=>myseoulCommand(bad));count++;}
eq(myseoulCommand({...c,restricted:true,scope:'capital',condition:'성남시 주민',evidence:['원문 성남시 주민']} ).scope,'capital');
let calls=[];const client={async rpc(name,args){calls.push({name,args});return{data:raw,error:null};}},store=new MySeoulReviewStore(client);
await store.execute(id,c,actor);eq(calls[0].name,'admin_myseoul_residence_confirm');eq(calls[0].args.p_actor,actor);eq(calls[0].args.p_request,rid);eq(calls[0].args.p_evidence,[]);
const url=`http://localhost:3228/api/admin/myseoul-review/${id}`,post=(body,origin='http://localhost:3228')=>new Request(url,{method:'POST',headers:{origin,'content-type':'application/json'},body:JSON.stringify(body)}),deps={authorize:async()=>({userId:actor}),store:()=>store};
let resp=await myseoulRequest(post(c),id,deps);eq(resp.status,200);ok(resp.headers.get('cache-control').includes('no-store'));let before=calls.length;resp=await myseoulRequest(post(c,'http://evil.invalid'),id,deps);eq(resp.status,403);eq(calls.length,before);resp=await myseoulRequest(post({...c,actor:'forged'}),id,deps);eq(resp.status,422);eq(calls.length,before);
await myseoulRequest(new Request(url),id,deps);eq(calls.at(-1).name,'admin_myseoul_program_detail');
const denied={...deps,authorize:async()=>{throw Error('denied');}};await myseoulRequest(post(c),id,denied);eq(calls.length,before+1);
const trash=new TrashStore({async rpc(name,args){calls.push({name,args});return{data:{episodeId:rid,expiresAt:'2099-10-15T00:00:00Z',item:{...raw,status:'excluded'}},error:null};}});
const body={action:'exclude',id,revision:c.revision,version:c.version,requestId:rid,reasonCode:'region_not_suitable',note:''};
resp=await trashRequest(new Request('http://localhost:3228/api/admin/review-trash',{method:'POST',headers:{origin:'http://localhost:3228','content-type':'application/json'},body:JSON.stringify(body)}),{authorize:deps.authorize,store:()=>trash});eq(resp.status,200);eq(calls.at(-1).name,'admin_review_exclude_reason');eq(calls.at(-1).args.p_actor,actor);eq(calls.at(-1).args.p_reason,'region_not_suitable');
const nodes=t=>[t,...React.Children.toArray(t?.props?.children).flatMap(n=>typeof n==='object'?nodes(n):[])],text=t=>typeof t==='string'||typeof t==='number'?String(t):React.Children.toArray(t?.props?.children).map(text).join('');
let submitted=[];const childProps={item,disabled:false,onDirty(){},onSave:c=>submitted.push(c),onRegionExclude(){}};
function renderChild(){cursor=0;refCursor=0;return Residence(childProps);}function find(tree,label){const n=nodes(tree).find(n=>n?.type==='button'&&text(n)===label);assert.ok(n,label);return n;}
states=[];refs=[];let tree=renderChild();ok(!nodes(tree).some(n=>n?.type==='textarea'));ok(!nodes(tree).find(n=>n?.type==='input').props.checked);eq(submitted.length,0);find(tree,'제한 없음으로 판단 · 확인·저장').props.onClick({currentTarget:{focus(){}}});find(renderChild(),'제한 없음으로 판단 · 확인·저장').props.onClick({currentTarget:{focus(){}}});eq(submitted.length,2);eq(submitted[0].requestId,submitted[1].requestId);eq(submitted[0].scope,'');eq(submitted[0].evidence,[]);
nodes(renderChild()).find(n=>n?.type==='input').props.onChange({target:{checked:true}});tree=renderChild();ok(nodes(tree).some(n=>n?.props?.id==='residence-condition'));ok(find(tree,'거주 조건 확인·저장').props.disabled);nodes(tree).find(n=>n?.props?.id==='residence-condition').props.onChange({target:{value:'성남시 주민'}});nodes(renderChild()).find(n=>n?.props?.id==='residence-evidence').props.onChange({target:{value:'원문 성남시 주민'}});tree=renderChild();ok(!find(tree,'거주 조건 확인·저장').props.disabled);find(tree,'거주 조건 확인·저장').props.onClick({currentTarget:{focus(){}}});eq(submitted.at(-1).restricted,true);eq(submitted.at(-1).condition,'성남시 주민');ok(submitted.at(-1).requestId!==submitted[0].requestId);find(tree,'판단할 수 없음').props.onClick({currentTarget:{focus(){}}});ok(find(renderChild(),'거주 조건 확인·저장').props.disabled);find(renderChild(),'원문 다시 확인하고 판단').props.onClick({currentTarget:{focus(){}}});ok(!find(renderChild(),'거주 조건 확인·저장').props.disabled);
states=[];refs=[];childProps.item={...item,facts:{...f,residence_scope:'capital',residence:'성남시 주민',residence_evidence:['원문 성남시 주민']}};tree=renderChild();ok(!nodes(tree).some(n=>n?.props?.id==='residence-evidence'));ok(text(tree).includes('원문 근거: 원문 성남시 주민'));
const originalFetch=globalThis.fetch;let posts=[],mode='fail';globalThis.fetch=async(url,o)=>{assert.equal(url,'/api/admin/review-trash');posts.push(JSON.parse(o.body));if(mode==='unknown')throw Error('response lost');return new Response(JSON.stringify(mode==='ok'?{mode:'database',item:{...raw,status:'excluded'}}:{code:mode==='expired'?'signed_out':'conflict'}),{status:mode==='ok'?200:mode==='expired'?401:409});};
function reset(){states=[item,structuredClone(f),null,false,0,'','',false,'','','','',false,false,false,null,false,'custom'];refs=[];}function render(){cursor=0;refCursor=0;return Panel({id,onBlocked(){},onResult(){}});}const settle=()=>new Promise(r=>setImmediate(r));
reset();find(render(),'대상 지역이 아님 · 제외').props.onClick({currentTarget:{focus(){}}});find(render(),'확인하고 제외').props.onClick({currentTarget:{focus(){}}});await settle();eq(posts.at(-1).reasonCode,'region_not_suitable');eq(posts.at(-1).note,'');const firstKey=posts.at(-1).requestId;eq(states[0].status,'open');mode='unknown';find(render(),'대상 지역이 아님 · 제외').props.onClick({currentTarget:{focus(){}}});find(render(),'확인하고 제외').props.onClick({currentTarget:{focus(){}}});await settle();eq(posts.at(-1).requestId,firstKey);eq(posts.length,2);eq(states[0].status,'open');mode='ok';find(render(),'대상 지역이 아님 · 제외').props.onClick({currentTarget:{focus(){}}});find(render(),'확인하고 제외').props.onClick({currentTarget:{focus(){}}});await settle();eq(states[0].status,'excluded');eq(posts.at(-1).requestId,firstKey);
reset();states[16]=true;ok(find(render(),'서비스에 적합하지 않음 · 제외').props.disabled);reset();states[11]='보존할 기타 사유';mode='expired';find(render(),'사유를 남기고 제외').props.onClick({currentTarget:{focus(){}}});find(render(),'확인하고 제외').props.onClick({currentTarget:{focus(){}}});await settle();eq(states[11],'보존할 기타 사유');eq(posts.at(-1).reasonCode,'custom');eq(posts.at(-1).note,'보존할 기타 사유');eq(states[0].status,'open');globalThis.fetch=originalFetch;

// Corrections found by the independent review: a server accept resets the child,
// custom exclusion input blocks the residence shortcut, and only a server DTO
// supplies confirmation status.
eq(myseoulItem({...raw,residenceReview:{confirmed:true,basis:'operator_no_restriction'}},id).residenceReview.confirmed,true);
eq(myseoulItem(raw,id).residenceReview.confirmed,false);
assert.throws(()=>myseoulItem({...raw,residenceReview:{confirmed:'yes',basis:'operator_no_restriction'}},id));count++;
reset();tree=render();let child=nodes(tree).find(n=>n?.type===Residence);ok(child);const childKey=child.key;
states[18]=1;child=nodes(render()).find(n=>n?.type===Residence);ok(child.key!==childKey);
reset();states[11]='보존할 기타 사유';child=nodes(render()).find(n=>n?.type===Residence);ok(child.props.regionExcludeDisabled);
states=[];refs=[];childProps.item=item;childProps.regionExcludeDisabled=true;
nodes(renderChild()).find(n=>n?.type==='input').props.onChange({target:{checked:true}});
nodes(renderChild()).find(n=>n?.props?.id==='residence-scope').props.onChange({target:{value:'noncapital_only'}});
ok(find(renderChild(),'대상 지역이 아님 · 제외 확인').props.disabled);
childProps.regionExcludeDisabled=false;ok(!find(renderChild(),'대상 지역이 아님 · 제외 확인').props.disabled);

console.log(JSON.stringify({checks:count,auth:'fake',rpc:'fake',providerCalls:0}));
