begin;
do $$ begin
if to_regprocedure('machimoa_review.classification_initial(uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_initial(uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'5f9c9bf80488ff83ce61c3dba6d7c7759b6f4f8e4dae63b35d7360da2ffcf646' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_initial(uuid)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_initial(uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_initial(uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_initial(uuid)';end if;
if to_regprocedure('public.admin_review_classification_detail(uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('public.admin_review_classification_detail(uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'721b5e3f1a3212db43e8507356ae734e5fa2dc050e1a4f397100cd2fbb198e3e' or (select proacl::text from pg_proc where oid=to_regprocedure('public.admin_review_classification_detail(uuid)')) is distinct from '{postgres=X/postgres,service_role=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('public.admin_review_classification_detail(uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('public.admin_review_classification_detail(uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','public.admin_review_classification_detail(uuid)';end if;
if to_regprocedure('machimoa_review.classification_validate(jsonb,jsonb)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_validate(jsonb,jsonb)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'1e01b8a6abd3907752d6298aacdf406becb5694a85b95c88f6c86f11c195e2cf' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_validate(jsonb,jsonb)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_validate(jsonb,jsonb)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_validate(jsonb,jsonb)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_validate(jsonb,jsonb)';end if;
if to_regprocedure('machimoa_review.classification_ready(uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_ready(uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'a7c3bfa08afcdd074791555cbf23c4b84d3b933cd0f38d17fbf12d54158c8ab9' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_ready(uuid)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_ready(uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_ready(uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_ready(uuid)';end if;
if to_regprocedure('machimoa_review.classification_native(uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_native(uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'fd1f88f8e33d65cf2a39bcf59f51fd2ac1f4e90d9eb08216683accadac7210e1' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_native(uuid)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_native(uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_native(uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_native(uuid)';end if;
if to_regprocedure('machimoa_review.classification_reasons(uuid,jsonb)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_reasons(uuid,jsonb)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'85a3d04d2359a278ee6a34d7717ed53fcad5fa4a12abb9f6fa01a545f31210af' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_reasons(uuid,jsonb)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_reasons(uuid,jsonb)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_reasons(uuid,jsonb)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_reasons(uuid,jsonb)';end if;
if to_regprocedure('public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'84a635a680140c0999528d01d9a413e05cd85ca92e05156ddb8887ab064ec10b' or (select proacl::text from pg_proc where oid=to_regprocedure('public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)')) is distinct from '{postgres=X/postgres,service_role=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','public.admin_review_reclassify(uuid,text,text,bigint,jsonb,jsonb,text,uuid)';end if;
if to_regprocedure('public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'ce54aa3ed8653e51fbc1b22a662c85594fcbb2e02f717ba8f4ab0fd43712dd90' or (select proacl::text from pg_proc where oid=to_regprocedure('public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)')) is distinct from '{postgres=X/postgres,service_role=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','public.claim_reclassified_content_ai(uuid,text,bigint,text,integer)';end if;
if to_regprocedure('machimoa_review.classification_candidate_guard(uuid)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.classification_candidate_guard(uuid)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'88902ccad191c2bcec9b1bfa8b4dacde7d854cac44869d6381df299210afa9e3' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.classification_candidate_guard(uuid)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.classification_candidate_guard(uuid)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.classification_candidate_guard(uuid)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.classification_candidate_guard(uuid)';end if;
if to_regprocedure('machimoa_review.content_filter_info(uuid,text)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.content_filter_info(uuid,text)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'aaa06964b2922f8776c2d7dbbfd896408dee78d35c007afb4815f0c5741fa2c6' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_info(uuid,text)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_info(uuid,text)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_info(uuid,text)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.content_filter_info(uuid,text)';end if;
if to_regprocedure('machimoa_review.content_filter_fact_values(uuid,text)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.content_filter_fact_values(uuid,text)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'2f0787341552437020be5ce2fb3f161a4587b57a6d617fa26aba155b93778f1a' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_fact_values(uuid,text)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_fact_values(uuid,text)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.content_filter_fact_values(uuid,text)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.content_filter_fact_values(uuid,text)';end if;
if to_regprocedure('machimoa_review.myseoul_residence_confirmed(jsonb)') is null or encode(sha256(convert_to(replace(replace(pg_get_functiondef(to_regprocedure('machimoa_review.myseoul_residence_confirmed(jsonb)')),E'\r\n',E'\n'),E'\r',E'\n'),'UTF8')),'hex')<>'eb8520eb1f5cbc57cff0c32d870580755747d452842e654c8a9fa7897b931542' or (select proacl::text from pg_proc where oid=to_regprocedure('machimoa_review.myseoul_residence_confirmed(jsonb)')) is distinct from '{postgres=X/postgres}' or (select pg_get_userbyid(proowner) from pg_proc where oid=to_regprocedure('machimoa_review.myseoul_residence_confirmed(jsonb)'))<>'postgres' or (select proconfig from pg_proc where oid=to_regprocedure('machimoa_review.myseoul_residence_confirmed(jsonb)')) is distinct from array['search_path=""']::text[] then raise exception 'continuity_predecessor_changed: %','machimoa_review.myseoul_residence_confirmed(jsonb)';end if;
if machimoa_review.classification_table_metadata('machimoa_review.review_classifications') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["source_item_id", "uuid", true, "", "", null], ["revision_hash", "text", true, "", "", null], ["classification_version", "bigint", true, "", "", null], ["facts", "jsonb", true, "", "", null], ["filters", "jsonb", false, "", "", null], ["native_snapshot", "text", true, "", "", null], ["note", "text", true, "", "", null], ["actor", "uuid", true, "", "", null], ["confirmed_at", "timestamp with time zone", true, "", "", "clock_timestamp()"]], "indexes": [["machimoa_review.review_classifications_pkey", "CREATE UNIQUE INDEX review_classifications_pkey ON machimoa_review.review_classifications USING btree (source_item_id, revision_hash)", true]], "forceRls": false, "policies": [], "constraints": [["review_classifications_classification_version_check", "CHECK ((classification_version > 0))", true], ["review_classifications_native_snapshot_check", "CHECK ((native_snapshot ~ ''^[a-f0-9]{64}$''::text))", true], ["review_classifications_pkey", "PRIMARY KEY (source_item_id, revision_hash)", true], ["review_classifications_source_item_id_fkey", "FOREIGN KEY (source_item_id) REFERENCES machimoa_review.source_items(id)", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','review_classifications';end if;
if machimoa_review.classification_table_metadata('machimoa_review.review_classification_history') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["source_item_id", "uuid", true, "", "", null], ["revision_hash", "text", true, "", "", null], ["classification_version", "bigint", true, "", "", null], ["previous", "jsonb", false, "", "", null], ["current", "jsonb", true, "", "", null], ["actor", "uuid", true, "", "", null], ["note", "text", true, "", "", null], ["at", "timestamp with time zone", true, "", "", "clock_timestamp()"]], "indexes": [["machimoa_review.review_classification_history_pkey", "CREATE UNIQUE INDEX review_classification_history_pkey ON machimoa_review.review_classification_history USING btree (source_item_id, revision_hash, classification_version)", true]], "forceRls": false, "policies": [], "constraints": [["review_classification_history_pkey", "PRIMARY KEY (source_item_id, revision_hash, classification_version)", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','review_classification_history';end if;
if machimoa_review.classification_table_metadata('machimoa_review.source_item_content_filters') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["source_item_id", "uuid", true, "", "", null], ["revision_hash", "text", true, "", "", null], ["filter_version", "bigint", true, "", "", "1"], ["data", "jsonb", true, "", "", null], ["observed_data", "jsonb", true, "", "", null], ["origins", "jsonb", true, "", "", null], ["evidence", "jsonb", true, "", "", null], ["source_binding", "jsonb", true, "", "", null], ["updated_at", "timestamp with time zone", true, "", "", "clock_timestamp()"]], "indexes": [["machimoa_review.source_item_content_filters_pkey", "CREATE UNIQUE INDEX source_item_content_filters_pkey ON machimoa_review.source_item_content_filters USING btree (source_item_id, revision_hash)", true]], "forceRls": false, "policies": [], "constraints": [["source_item_content_filters_filter_version_check", "CHECK ((filter_version > 0))", true], ["source_item_content_filters_pkey", "PRIMARY KEY (source_item_id, revision_hash)", true], ["source_item_content_filters_source_item_id_fkey", "FOREIGN KEY (source_item_id) REFERENCES machimoa_review.source_items(id)", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','source_item_content_filters';end if;
if machimoa_review.classification_table_metadata('machimoa_review.myseoul_residence_reviews') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["request_id", "uuid", true, "", "", null], ["event_id", "bigint", true, "", "", null], ["source_item_id", "uuid", true, "", "", null], ["revision_hash", "text", true, "", "", null], ["context_hash", "text", true, "", "", null], ["decision", "text", true, "", "", null], ["actor", "uuid", true, "", "", null], ["input", "jsonb", true, "", "", null], ["active", "boolean", true, "", "", "true"], ["confirmed_at", "timestamp with time zone", true, "", "", "clock_timestamp()"]], "indexes": [["machimoa_review.myseoul_residence_active", "CREATE UNIQUE INDEX myseoul_residence_active ON machimoa_review.myseoul_residence_reviews USING btree (source_item_id, revision_hash) WHERE active", true], ["machimoa_review.myseoul_residence_reviews_event_id_key", "CREATE UNIQUE INDEX myseoul_residence_reviews_event_id_key ON machimoa_review.myseoul_residence_reviews USING btree (event_id)", true], ["machimoa_review.myseoul_residence_reviews_pkey", "CREATE UNIQUE INDEX myseoul_residence_reviews_pkey ON machimoa_review.myseoul_residence_reviews USING btree (request_id)", true]], "forceRls": false, "policies": [], "constraints": [["myseoul_residence_reviews_context_hash_check", "CHECK ((context_hash ~ ''^[a-f0-9]{64}$''::text))", true], ["myseoul_residence_reviews_decision_check", "CHECK ((decision = ANY (ARRAY[''no_restriction''::text, ''restricted''::text])))", true], ["myseoul_residence_reviews_event_id_fkey", "FOREIGN KEY (event_id) REFERENCES machimoa_review.admin_review_events(id)", true], ["myseoul_residence_reviews_event_id_key", "UNIQUE (event_id)", true], ["myseoul_residence_reviews_pkey", "PRIMARY KEY (request_id)", true], ["myseoul_residence_reviews_revision_hash_check", "CHECK ((revision_hash ~ ''^[a-f0-9]{64}$''::text))", true], ["myseoul_residence_reviews_source_item_id_fkey", "FOREIGN KEY (source_item_id) REFERENCES machimoa_review.source_items(id)", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','myseoul_residence_reviews';end if;
if machimoa_review.classification_table_metadata('machimoa_review.myseoul_fact_edits') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["event_id", "bigint", true, "", "", null], ["before_patch", "jsonb", true, "", "", null], ["after_patch", "jsonb", true, "", "", null], ["activity_confirmed", "boolean", true, "", "", "false"]], "indexes": [["machimoa_review.myseoul_fact_edits_pkey", "CREATE UNIQUE INDEX myseoul_fact_edits_pkey ON machimoa_review.myseoul_fact_edits USING btree (event_id)", true]], "forceRls": false, "policies": [], "constraints": [["myseoul_fact_edits_after_patch_check", "CHECK ((jsonb_typeof(after_patch) = ''object''::text))", true], ["myseoul_fact_edits_before_patch_check", "CHECK ((jsonb_typeof(before_patch) = ''object''::text))", true], ["myseoul_fact_edits_event_id_fkey", "FOREIGN KEY (event_id) REFERENCES machimoa_review.admin_review_events(id) ON DELETE RESTRICT", true], ["myseoul_fact_edits_pkey", "PRIMARY KEY (event_id)", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','myseoul_fact_edits';end if;
if machimoa_review.classification_table_metadata('machimoa_review.source_item_program_facts') is distinct from '{"acl": "{postgres=arwdDxtm/postgres}", "rls": true, "owner": "postgres", "columns": [["source_item_id", "uuid", true, "", "", null], ["revision_hash", "text", true, "", "", null], ["schema_version", "text", true, "", "", "''program-scope-v1-local''::text"], ["evaluated_profile", "text", true, "", "", "''program_capital_v1_local''::text"], ["source_snapshot", "jsonb", true, "", "", null], ["observed_facts", "jsonb", true, "", "", null], ["facts", "jsonb", true, "", "", null], ["facts_version", "bigint", true, "", "", "1"], ["manual_excluded", "boolean", true, "", "", "false"], ["result", "jsonb", true, "", "", "''{}''::jsonb"], ["updated_by", "uuid", false, "", "", null], ["updated_at", "timestamp with time zone", true, "", "", "clock_timestamp()"]], "indexes": [["machimoa_review.source_item_program_facts_pkey", "CREATE UNIQUE INDEX source_item_program_facts_pkey ON machimoa_review.source_item_program_facts USING btree (source_item_id, revision_hash)", true]], "forceRls": false, "policies": [], "constraints": [["program_facts_schema_profile_pair_ck", "CHECK ((((schema_version = ''program-scope-v1-local''::text) AND (evaluated_profile = ''program_capital_v1_local''::text)) OR ((schema_version = ''myseoul-program-facts-v1-local''::text) AND (evaluated_profile = ''myseoul-program-v1-local''::text))))", true], ["source_item_program_facts_pkey", "PRIMARY KEY (source_item_id, revision_hash)", true], ["source_item_program_facts_revision_hash_check", "CHECK ((revision_hash ~ ''^[a-f0-9]{64}$''::text))", true], ["source_item_program_facts_source_item_id_fkey", "FOREIGN KEY (source_item_id) REFERENCES machimoa_review.source_items(id) ON DELETE RESTRICT", true]]}'::jsonb then raise exception 'continuity_predecessor_schema_changed: %','source_item_program_facts';end if;
if to_regclass('machimoa_review.review_continuity_install') is not null or to_regprocedure('machimoa_review.classification_draft(uuid,text)') is not null or to_regprocedure('machimoa_review.review_continuity_dirty()') is not null then raise exception 'continuity_name_collision';end if;
end $$;
CREATE OR REPLACE FUNCTION machimoa_review.classification_initial(p_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE
 SET search_path TO ''
AS $function$
declare s machimoa_review.source_items%rowtype;f jsonb;g jsonb;cat text;pt text;v jsonb;scope text;regions jsonb;evidence text;dk text;de text;es text;ee text;
begin
 select * into s from machimoa_review.source_items where id=p_id;
 if not found then raise sqlstate 'PT404' using message='review_not_found';end if;
 select facts into f from machimoa_review.source_item_program_facts where source_item_id=p_id and revision_hash=s.revision_hash;
 select product_type,gate_facts into pt,g from machimoa_review.source_item_product_types where source_item_id=p_id and revision_hash=s.revision_hash;
 cat:=machimoa_review.content_filter_category(p_id,s.revision_hash);
 if cat not in ('policy','program','event','youth_space','living') or cat is null then cat:='';end if;
 if pt not in ('event_program','policy_reference','living_guide') or pt is null then pt:=case when f is not null then 'event_program' else '' end;end if;
 scope:=coalesce(g->>'eligibility_scope','unknown');regions:=coalesce(g->'eligibility_region_codes','[]');evidence:=coalesce(g->>'eligibility_region_evidence','');
 if f is not null then
 scope:=case f->>'residence_scope' when 'nationwide' then 'nationwide' when 'capital' then 'specific' when 'includes_capital' then 'specific' else 'unknown' end;
 regions:=case when scope='specific' then '["11","28","41"]'::jsonb else '[]'::jsonb end;
 evidence:=left(coalesce((select string_agg(value#>>'{}',E'\n') from jsonb_array_elements(coalesce(f->'residence_evidence','[]'))),''),500);
 end if;
 if scope in ('unknown','nationwide') and coalesce(evidence,'')='' and f->>'delivery_mode'='online' and machimoa_review.myseoul_residence_confirmed(f) then
 scope:='nationwide';regions:='[]';evidence:='운영자 판단: 원문 대상·신청 조건을 확인하여 거주 지역 제한이 없다고 확인함.';
end if;
v:=machimoa_review.content_filter_fact_values(p_id,s.revision_hash);
 if cat in ('policy','program') then
 select application_deadline_kind,application_deadline_on::text into dk,de from machimoa_review.source_item_application_deadlines where source_item_id=p_id and revision_hash=s.revision_hash;
 if v ? 'application' then dk:=v->'application'->>'deadlineKind';de:=v->'application'->'end'->>'value';end if;
 end if;
 if cat='event' then select event_start_on::text,event_end_on::text into es,ee from machimoa_review.source_item_event_periods where source_item_id=p_id and revision_hash=s.revision_hash;end if;
 return jsonb_build_object('productType',pt,'category',cat,'scope',scope,'regions',regions,'evidence',evidence,
 'foreignEligibility',coalesce(g->>'foreign_resident_eligibility','unknown'),'delivery',case coalesce(f->>'delivery_mode',g->>'delivery_mode') when 'mixed' then 'hybrid' when 'hybrid' then 'hybrid' when 'online' then 'online' when 'offline' then 'offline' else 'unknown' end,
 'deadlineKind',coalesce(dk,''),'deadlineOn',case when dk='fixed' then left(coalesce(de,''),10) else '' end,'eventStart',coalesce(es,''),'eventEnd',coalesce(ee,''));
end $function$
;

create function machimoa_review.classification_draft(p_id uuid,p_category text) returns jsonb
language plpgsql stable set search_path='' as $$
declare s machimoa_review.source_items%rowtype;f jsonb;pf jsonb;b jsonb;d jsonb;k text;v jsonb;a jsonb;period jsonb;es text;ee text;
begin
 if p_category not in ('policy','program','event','youth_space','living') then raise sqlstate 'PT422' using message='classification_invalid_category';end if;
 select * into s from machimoa_review.source_items where id=p_id;
 if not found then raise sqlstate 'PT404' using message='review_not_found';end if;
 select facts,filters into f,b from machimoa_review.review_classifications where source_item_id=p_id and revision_hash=s.revision_hash;
 if f->>'category'=p_category then return jsonb_build_object('facts',f,'filters',b);end if;
 f:=machimoa_review.classification_initial(p_id)||jsonb_build_object('category',p_category,'productType',case p_category when 'living' then 'living_guide' when 'policy' then 'policy_reference' else 'event_program' end,'deadlineKind','','deadlineOn','','eventStart','','eventEnd','');
 select facts into pf from machimoa_review.source_item_program_facts where source_item_id=p_id and revision_hash=s.revision_hash;
 if b is null then select data into b from machimoa_review.source_item_content_filters where source_item_id=p_id and revision_hash=s.revision_hash;end if;
 v:=machimoa_review.content_filter_fact_values(p_id,s.revision_hash);
 d:=null;
 if p_category in ('program','event','youth_space') then
 d:=jsonb_build_object('schema','content-filters-v1','category',p_category);
 foreach k in array array['topic','location','delivery','audience','spaceKind','application','schedule'] loop
 d:=d||jsonb_build_object(k,jsonb_build_object('status',case when (p_category='program' and k in ('spaceKind','schedule')) or (p_category='event' and k in ('delivery','audience','spaceKind','application')) or (p_category='youth_space' and k in ('topic','delivery','audience','application','schedule')) then 'not_applicable' else 'unknown' end,'value',null));
 end loop;
 foreach k in array array['topic','location','delivery','audience','spaceKind','application','schedule'] loop
 if d->k->>'status'='unknown' and b->k->>'status'='known' and (b->>'category'=p_category or k='location' or k='topic' and b->k->>'value'='other') then d:=jsonb_set(d,array[k],b->k);end if;
 end loop;
 if p_category='program' then
 foreach k in array array['delivery','application'] loop
 if d->k->>'status'='unknown' and v ? k then d:=jsonb_set(d,array[k],jsonb_build_object('status','known','value',v->k));end if;end loop;
 if d->'delivery'->>'value'='online' then d:=jsonb_set(d,'{location}','{"status":"not_applicable","value":null}');end if;
 if d->'application'->>'status'='known' then a:=d->'application'->'value';f:=f||jsonb_build_object('deadlineKind',a->>'deadlineKind','deadlineOn',case when a->>'deadlineKind'='fixed' then left(a->'end'->>'value',10) else '' end);end if;
 elsif p_category='event' then
 if d->'schedule'->>'status'='unknown' and jsonb_typeof(pf->'periods'->'operation')='array' and not exists(select 1 from jsonb_array_elements(pf->'issues') x where x->>'code' in ('source_fact_conflict:operation','source_change_conflict:operation')) then
 select value into period from jsonb_array_elements(pf->'periods'->'operation') where value->>'status'='ok' and jsonb_array_length(value->'endpoints')=2;
 if period is not null and (select count(distinct x->'endpoints') from jsonb_array_elements(pf->'periods'->'operation') x where x->>'status'='ok')=1 then
 d:=jsonb_set(d,'{schedule}',jsonb_build_object('status','known','value',jsonb_build_object('kind','continuous','recurrence',null,'occurrences',jsonb_build_array(jsonb_build_object('start',period->'endpoints'->0,'end',period->'endpoints'->1)))));
 end if;end if;
 if d->'schedule'->>'status'='unknown' then
 select event_start_on::text,event_end_on::text into es,ee from machimoa_review.source_item_event_periods where source_item_id=p_id and revision_hash=s.revision_hash;
 if es is not null and ee is not null then d:=jsonb_set(d,'{schedule}',jsonb_build_object('status','known','value',jsonb_build_object('kind','continuous','recurrence',null,'occurrences',jsonb_build_array(jsonb_build_object('start',jsonb_build_object('value',es,'precision','day'),'end',jsonb_build_object('value',ee,'precision','day'))))));end if;end if;
 if d->'schedule'->>'status'='known' then
 select min(left(x->'start'->>'value',10)),max(left(x->'end'->>'value',10)) into es,ee from jsonb_array_elements(d->'schedule'->'value'->'occurrences') x;
 f:=f||jsonb_build_object('eventStart',coalesce(es,''),'eventEnd',coalesce(ee,''));end if;
 end if;
 perform machimoa_review.content_filter_validate(d);
 elsif p_category='policy' then
 select application_deadline_kind,application_deadline_on::text into es,ee from machimoa_review.source_item_application_deadlines where source_item_id=p_id and revision_hash=s.revision_hash;
 if v ? 'application' then es:=v->'application'->>'deadlineKind';ee:=left(v->'application'->'end'->>'value',10);end if;
 f:=f||jsonb_build_object('deadlineKind',coalesce(es,''),'deadlineOn',case when es='fixed' then coalesce(ee,'') else '' end);
 end if;
 return jsonb_build_object('facts',f,'filters',d);
end $$;
CREATE OR REPLACE FUNCTION public.admin_review_classification_detail(p_id uuid)
 RETURNS jsonb
 LANGUAGE plpgsql
 STABLE SECURITY DEFINER
 SET search_path TO ''
AS $function$
declare s machimoa_review.source_items%rowtype;c machimoa_review.review_classifications%rowtype;f jsonb;d jsonb;v text;reasons text[];editable boolean;requested_id uuid:=p_id;pub jsonb;
begin
 p_id:=machimoa_review.classification_source(p_id);
 select * into s from machimoa_review.source_items where id=p_id;if not found then raise sqlstate 'PT404' using message='review_not_found';end if;
 select * into c from machimoa_review.review_classifications where source_item_id=p_id and revision_hash=s.revision_hash;
 f:=coalesce(c.facts,machimoa_review.classification_initial(p_id));
 if c.source_item_id is not null then d:=c.filters;else d:=machimoa_review.content_filter_info(p_id,s.revision_hash)->'data';if f->>'category' not in ('program','event','youth_space') then d:=null;end if;end if;
 pub:=machimoa_review.classification_publication(p_id);
 v:=encode(sha256(convert_to(jsonb_build_array(machimoa_review.admin_review_snapshot('facts',p_id),to_jsonb(c),pub)::text,'UTF8')),'hex');
 reasons:=case when c.source_item_id is null then '{}'::text[] when c.native_snapshot<>machimoa_review.classification_native(p_id) then array['classification_input_changed'] else '{}'::text[] end;
 if f->>'category'='program' and (f->>'deadlineKind' is distinct from 'fixed' or d is null or 'application'=any(machimoa_review.classification_filter_missing(d))) then reasons:=array_append(reasons,'content_filter:application');end if;
 editable:=not exists(select 1 from machimoa_review.processing_jobs where source_item_id=p_id and status='claimed') and
 not exists(select 1 from machimoa_review.source_item_program_facts pf where pf.source_item_id=p_id and pf.revision_hash=s.revision_hash and pf.manual_excluded) and
 s.disposition not in ('non_target','excluded','outside_scope') and not machimoa_review.admin_trash_pending(p_id,s.revision_hash);
 return jsonb_build_object('id',requested_id,'publication',pub,'revision',s.revision_hash,'version',v,'classificationVersion',coalesce(c.classification_version,0),'active',c.source_item_id is not null,
 'category',f->>'category','facts',f,'filters',d,'drafts',(select jsonb_object_agg(cat,machimoa_review.classification_draft(p_id,cat)) from unnest(array['policy','program','event','youth_space','living']) cat),'note',coalesce(c.note,''),'editable',editable,'ready',machimoa_review.classification_ready(p_id),'reasons',to_jsonb(reasons),'sourceReasons',to_jsonb(array(select distinct code from unnest(machimoa_review.classification_reasons(p_id,f)||array(select unnest(j.reason_codes) from machimoa_review.processing_jobs j where j.source_item_id=p_id and j.revision_hash=s.revision_hash and j.processing_stage<>'ai_enrichment' and j.status in ('queued','claimed'))) code)));
end $function$
;
create table machimoa_review.review_continuity_install(singleton boolean primary key check(singleton),dirty boolean not null default false);
alter table machimoa_review.review_continuity_install enable row level security;
revoke all on machimoa_review.review_continuity_install from public,anon,authenticated,service_role;
insert into machimoa_review.review_continuity_install values(true,false);
create function machimoa_review.review_continuity_dirty() returns trigger language plpgsql set search_path='' as $$begin update machimoa_review.review_continuity_install set dirty=true;return null;end $$;
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.review_classifications for each statement execute function machimoa_review.review_continuity_dirty();
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.review_classification_history for each statement execute function machimoa_review.review_continuity_dirty();
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.source_item_content_filters for each statement execute function machimoa_review.review_continuity_dirty();
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.myseoul_residence_reviews for each statement execute function machimoa_review.review_continuity_dirty();
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.myseoul_fact_edits for each statement execute function machimoa_review.review_continuity_dirty();
create trigger review_continuity_dirty after insert or update or delete on machimoa_review.source_item_program_facts for each statement execute function machimoa_review.review_continuity_dirty();
revoke all on function machimoa_review.classification_draft(uuid,text),machimoa_review.review_continuity_dirty() from public,anon,authenticated,service_role;
notify pgrst,'reload schema';commit;
